import { useState, useEffect, useRef, useCallback } from "react";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { useAuth, useUser } from "@clerk/react";
import { useRoute } from "wouter";
import { useWorkspace } from "@/contexts/WorkspaceContext";
import { authFetch } from "@/lib/authFetch";
import { PhotoUploadSection } from "@/components/InvitationCustomization/PhotoUploadSection";
import { ColorSystemSection } from "@/components/InvitationCustomization/ColorSystemSection";
import { DesignOptionsSection } from "@/components/InvitationCustomization/DesignOptionsSection";
import { SaveTheDatePreview } from "@/components/InvitationCustomization/SaveTheDatePreview";
import { RsvpPagePreview } from "@/components/InvitationCustomization/RsvpPagePreview";
import {
  AiSaveDatePreview,
} from "@/components/InvitationCustomization/AiPreviewComponents";
import { Card, CardContent } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { useToast } from "@/hooks/use-toast";
import { Tabs, TabsList, TabsTrigger } from "@/components/ui/tabs";
import {
  Loader2,
  RotateCcw,
  Sparkles,
  Paintbrush,
  ChevronDown,
  ChevronUp,
  RefreshCw,
  Save,
} from "lucide-react";
import { Textarea } from "@/components/ui/textarea";
import type {
  InvitationCustomization,
  ColorPalette,
  PreviewTab,
  WeddingProfileData,
  TextOverrides,
} from "@/types/invitations";

interface RouteParams {
  [key: string]: string | undefined;
  profileId?: string;
}

interface InvitationCustomizationProps {
  profileId?: number;
}

export default function InvitationCustomizationPage({
  profileId: propProfileId,
}: InvitationCustomizationProps = {}) {
  const { getToken } = useAuth();
  const { user } = useUser();
  const { toast } = useToast();
  const { activeWorkspace } = useWorkspace();
  const queryClient = useQueryClient();
  const [, params] = useRoute<RouteParams>("/guests/:profileId");

  const profileId =
    propProfileId ||
    (params?.profileId
      ? parseInt(params.profileId)
      : activeWorkspace?.profileId);
  const [previewTab, setPreviewTab] = useState<PreviewTab>("saveTheDate");

  // ── Shared brand-color state ──────────────────────────────────────────────
  // Default palette matches the dark-navy + gold aesthetic shown in the app.
  const [primaryColor, setPrimaryColor] = useState("#D4A017");
  const [autoGeneratedPalette, setAutoGeneratedPalette] =
    useState<ColorPalette>({
      primary: "#D4A017",
      secondary: "#F5C842",
      accent: "#D4A017",
      neutral: "#E8E0D0",
    });
  const [customColors, setCustomColors] =
    useState<Partial<ColorPalette> | null>(null);
  const [selectedPalette, setSelectedPalette] = useState<string | null>(null);
  const [backgroundImageUrl, setBackgroundImageUrl] = useState<string | null>(
    null,
  );

  // ── Save the Date ─────────────────────────────────────────────────────────
  const [saveTheDatePhotoUrl, setSaveTheDatePhotoUrl] = useState<string | null>(
    null,
  );
  const [saveTheDateFont, setSaveTheDateFont] = useState("Playfair Display");
  const [saveTheDateLayout, setSaveTheDateLayout] = useState("classic");
  const [saveTheDateBackground, setSaveTheDateBackground] = useState<
    string | null
  >("#1E1A2E");
  const [stdTextOverrides, setStdTextOverrides] = useState<TextOverrides>({});

  // ── Digital Invitation ────────────────────────────────────────────────────
  const [digitalInvitationPhotoUrl, setDigitalInvitationPhotoUrl] = useState<
    string | null
  >(null);
  const [digitalInvitationFont, setDigitalInvitationFont] =
    useState("Playfair Display");
  const [digitalInvitationLayout, setDigitalInvitationLayout] =
    useState("classic");
  const [digitalInvitationBackground, setDigitalInvitationBackground] =
    useState<string | null>("#1E1A2E");
  const [digTextOverrides, setDigTextOverrides] = useState<TextOverrides>({});

  // ── Photo position (AI mode only — drag to reposition within frame) ─────────
  const [saveTheDatePhotoPosition, setSaveTheDatePhotoPosition] = useState({
    x: 50,
    y: 50,
  });
  const [digitalInvitationPhotoPosition, setDigitalInvitationPhotoPosition] =
    useState({ x: 50, y: 50 });

  // ── Invitation mode ───────────────────────────────────────────────────────
  // true = use AI-generated email template  |  false = use user's custom design
  const [useGeneratedInvitation, setUseGeneratedInvitation] = useState(true);

  // ── Messages ──────────────────────────────────────────────────────────────
  const [saveTheDateMessage, setSaveTheDateMessage] = useState("");
  const [invitationMessage, setInvitationMessage] = useState("");
  const [showStdAiPanel, setShowStdAiPanel] = useState(false);
  const [stdAiDetails, setStdAiDetails] = useState("");
  const [stdGenerating, setStdGenerating] = useState(false);
  const [showDigAiPanel, setShowDigAiPanel] = useState(false);
  const [digAiDetails, setDigAiDetails] = useState("");
  const [digGenerating, setDigGenerating] = useState(false);
  const [savingMessage, setSavingMessage] = useState(false);

  // ── Misc ──────────────────────────────────────────────────────────────────
  const skipNextAutoSave = useRef(true);
  const hasInitialized = useRef(false);
  // Cached Clerk token so the unmount save can fire synchronously without
  // awaiting (which would let the page tear down before the fetch is issued).
  const tokenRef = useRef<string | null>(null);
  // Holds the latest values for the unmount-save so we don't capture stale closures
  const latestValuesRef = useRef({
    profileId,
    primaryColor,
    autoGeneratedPalette,
    customColors,
    selectedPalette,
    saveTheDatePhotoUrl,
    saveTheDatePhotoPosition,
    saveTheDateFont,
    saveTheDateLayout,
    saveTheDateBackground,
    stdTextOverrides,
    digitalInvitationPhotoUrl,
    digitalInvitationPhotoPosition,
    digitalInvitationFont,
    digitalInvitationLayout,
    digitalInvitationBackground,
    digTextOverrides,
    backgroundImageUrl,
    useGeneratedInvitation,
  });
  const saveTheDatePreviewRef = useRef<HTMLDivElement>(null);
  const saveTheDateBlobUrlRef = useRef<string | null>(null);
  const digitalInvitationBlobUrlRef = useRef<string | null>(null);
  const previewContainerRef = useRef<HTMLDivElement>(null);
  const [previewContainerWidth, setPreviewContainerWidth] = useState(0);

  useEffect(() => {
    const el = previewContainerRef.current;
    if (!el) return;
    const observer = new ResizeObserver((entries) => {
      setPreviewContainerWidth(entries[0]?.contentRect.width ?? 0);
    });
    observer.observe(el);
    return () => observer.disconnect();
  }, []);

  // Keep ref current on every render so the unmount effect always has latest values
  latestValuesRef.current = {
    profileId,
    primaryColor,
    autoGeneratedPalette,
    customColors,
    selectedPalette,
    saveTheDatePhotoUrl,
    saveTheDatePhotoPosition,
    saveTheDateFont,
    saveTheDateLayout,
    saveTheDateBackground,
    stdTextOverrides,
    digitalInvitationPhotoUrl,
    digitalInvitationPhotoPosition,
    digitalInvitationFont,
    digitalInvitationLayout,
    digitalInvitationBackground,
    digTextOverrides,
    backgroundImageUrl,
    useGeneratedInvitation,
  };

  useEffect(() => {
    return () => {
      if (saveTheDateBlobUrlRef.current)
        URL.revokeObjectURL(saveTheDateBlobUrlRef.current);
      if (digitalInvitationBlobUrlRef.current)
        URL.revokeObjectURL(digitalInvitationBlobUrlRef.current);
    };
  }, []);

  // ── Save on unmount so navigating away never drops unsaved changes ──────────
  useEffect(() => {
    return () => {
      const v = latestValuesRef.current;
      if (!v.profileId) return;
      if (v.saveTheDatePhotoUrl?.startsWith("blob:")) return;
      if (v.digitalInvitationPhotoUrl?.startsWith("blob:")) return;
      const body = JSON.stringify({
        profileId: v.profileId,
        primaryColor: v.primaryColor,
        colorPalette: v.autoGeneratedPalette,
        customColors: v.customColors,
        selectedPalette: v.selectedPalette,
        backgroundColor: v.saveTheDateBackground,
        selectedFont: v.saveTheDateFont,
        selectedLayout: v.saveTheDateLayout,
        saveTheDatePhotoUrl: v.saveTheDatePhotoUrl,
        digitalInvitationPhotoUrl: v.digitalInvitationPhotoUrl,
        saveTheDatePhotoPosition: v.saveTheDatePhotoPosition,
        digitalInvitationPhotoPosition: v.digitalInvitationPhotoPosition,
        saveTheDateFont: v.saveTheDateFont,
        digitalInvitationFont: v.digitalInvitationFont,
        saveTheDateLayout: v.saveTheDateLayout,
        digitalInvitationLayout: v.digitalInvitationLayout,
        saveTheDateBackground: v.saveTheDateBackground,
        digitalInvitationBackground: v.digitalInvitationBackground,
        backgroundImageUrl: v.backgroundImageUrl,
        textOverrides: { ...v.stdTextOverrides, ...v.digTextOverrides },
        useGeneratedInvitation: v.useGeneratedInvitation,
      });

      const apiBase = (import.meta.env.VITE_API_URL ?? "").replace(/\/+$/, "");
      const saveUrl = `${apiBase}/api/invitation-customizations`;

      const cachedToken = tokenRef.current;
      if (cachedToken) {
        fetch(saveUrl, {
          method: "POST",
          credentials: "include",
          keepalive: true,
          headers: {
            "Content-Type": "application/json",
            Authorization: `Bearer ${cachedToken}`,
          },
          body,
        }).catch(() => {});
      } else if (typeof navigator !== "undefined" && navigator.sendBeacon) {
        try {
          navigator.sendBeacon(
            saveUrl,
            new Blob([body], { type: "application/json" }),
          );
        } catch {
          // ignore — best-effort
        }
      }
    };
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, []); // empty deps — fires only on unmount

  // Persist a single field immediately, surviving navigation via keepalive.
  // Used for the design-mode toggle so leaving the page right after clicking
  // doesn't lose the choice (the 1s debounce wouldn't have fired yet).
  const persistDesignMode = useCallback(
    async (useAi: boolean) => {
      const v = latestValuesRef.current;
      if (!v.profileId) return;
      try {
        const token = await getToken();
        if (token) tokenRef.current = token;
        const apiBase = (import.meta.env.VITE_API_URL ?? "").replace(
          /\/+$/,
          "",
        );
        await fetch(`${apiBase}/api/invitation-customizations`, {
          method: "POST",
          credentials: "include",
          keepalive: true,
          headers: {
            "Content-Type": "application/json",
            ...(token ? { Authorization: `Bearer ${token}` } : {}),
          },
          body: JSON.stringify({
            profileId: v.profileId,
            useGeneratedInvitation: useAi,
          }),
        });
      } catch {
        // best-effort — the autosave/unmount-save will retry on next render
      }
    },
    [getToken],
  );

  const handleSelectDesignMode = useCallback(
    (useAi: boolean) => {
      setUseGeneratedInvitation(useAi);
      skipNextAutoSave.current = true; // we are persisting directly here
      // Keep the React Query cache in sync so navigating away and back
      // doesn't reload the stale value (the customization query is cached
      // with staleTime: Infinity).
      queryClient.setQueryData(
        ["invitation-customizations", profileId],
        (old: InvitationCustomization | null | undefined) =>
          old ? { ...old, useGeneratedInvitation: useAi } : old,
      );
      void persistDesignMode(useAi);
    },
    [persistDesignMode, queryClient, profileId],
  );

  const authedFetch = async (url: string, init: RequestInit = {}) => {
    const token = await getToken();
    if (token) tokenRef.current = token;
    return authFetch(url, {
      ...init,
      credentials: "include",
      headers: {
        ...(!(init.body instanceof FormData)
          ? { "Content-Type": "application/json" }
          : {}),
        ...(init.headers ?? {}),
        ...(token ? { Authorization: `Bearer ${token}` } : {}),
      },
    });
  };

  const setCustomizationCache = useCallback(
    (
      updater: (
        old: InvitationCustomization | null | undefined,
      ) => InvitationCustomization | null | undefined,
    ) => {
      if (!profileId) return;
      queryClient.setQueryData(
        ["invitation-customizations", profileId],
        updater,
      );
    },
    [profileId, queryClient],
  );

  const resetPhotoObjectPosition = (
    overrides: TextOverrides | undefined,
    id: "std:photo" | "dig:photo",
  ): TextOverrides => {
    if (!overrides?.[id]) return overrides ?? {};
    const rest = { ...overrides[id] };
    delete rest.objectX;
    delete rest.objectY;
    const next = { ...overrides };
    if (Object.keys(rest).length === 0) {
      delete next[id];
    } else {
      next[id] = rest;
    }
    return next;
  };

  // ── Queries ───────────────────────────────────────────────────────────────
  const { data: weddingProfile } = useQuery({
    queryKey: ["wedding-profile", profileId],
    queryFn: async () => {
      if (!profileId) return null;
      const r = await authedFetch(`/api/profile`);
      if (!r.ok) throw new Error("Failed to fetch profile");
      return r.json() as Promise<WeddingProfileData>;
    },
    enabled: !!profileId,
    retry: 1,
  });

  const { data: customization } = useQuery({
    queryKey: ["invitation-customizations", profileId],
    queryFn: async () => {
      if (!profileId) return null;
      const r = await authedFetch(
        `/api/invitation-customizations?profileId=${profileId}`,
      );
      if (!r.ok) throw new Error("Failed to fetch customizations");
      return r.json() as Promise<InvitationCustomization>;
    },
    enabled: !!profileId,
    staleTime: 0,
    refetchOnMount: "always",
    refetchOnWindowFocus: true,
  });

  // ── Load DB data into state ───────────────────────────────────────────────
  useEffect(() => {
    if (!customization) return;

    if (!hasInitialized.current) {
      hasInitialized.current = true;
      skipNextAutoSave.current = true;

      // Shared
      setPrimaryColor(customization.primaryColor);
      setAutoGeneratedPalette(customization.colorPalette);
      setCustomColors(customization.customColors);
      setSelectedPalette(customization.selectedPalette);
      setBackgroundImageUrl(customization.backgroundImageUrl);

      // Per-design photos
      setSaveTheDatePhotoUrl(customization.saveTheDatePhotoUrl);
      setDigitalInvitationPhotoUrl(customization.digitalInvitationPhotoUrl);

      // Per-design photo positions — default to center if never saved
      if (customization.saveTheDatePhotoPosition) {
        setSaveTheDatePhotoPosition(customization.saveTheDatePhotoPosition);
      }
      if (customization.digitalInvitationPhotoPosition) {
        setDigitalInvitationPhotoPosition(
          customization.digitalInvitationPhotoPosition,
        );
      }

      // Per-design fonts
      setSaveTheDateFont(
        customization.saveTheDateFont ||
          customization.selectedFont ||
          "Georgia",
      );
      setDigitalInvitationFont(
        customization.digitalInvitationFont ||
          customization.selectedFont ||
          "Georgia",
      );

      // Per-design layout
      setSaveTheDateLayout(
        customization.saveTheDateLayout ||
          customization.selectedLayout ||
          "classic",
      );
      setDigitalInvitationLayout(
        customization.digitalInvitationLayout ||
          customization.selectedLayout ||
          "classic",
      );

      // Per-design background — default to dark navy if nothing was ever saved
      setSaveTheDateBackground(
        customization.saveTheDateBackground ??
          customization.backgroundColor ??
          "#1E1A2E",
      );
      setDigitalInvitationBackground(
        customization.digitalInvitationBackground ??
          customization.backgroundColor ??
          "#1E1A2E",
      );

      // Split text overrides by prefix
      const allOverrides = customization.textOverrides || {};
      const stdOverrides: TextOverrides = {};
      const digOverrides: TextOverrides = {};
      for (const [key, val] of Object.entries(allOverrides)) {
        if (key.startsWith("std:")) stdOverrides[key] = val;
        else if (key.startsWith("dig:")) digOverrides[key] = val;
      }
      setStdTextOverrides(stdOverrides);
      setDigTextOverrides(digOverrides);

      // Invitation mode — default to true if field isn't stored yet
      setUseGeneratedInvitation(customization.useGeneratedInvitation ?? true);
    } else {
      // After the first full init, still sync photo URLs from subsequent DB
      // fetches (e.g. background refetch on window focus). We only apply the
      // DB value when our current state is null / a blob (meaning the upload
      // hasn't completed yet and the DB already has the canonical URL), or
      // when the DB returns a URL that's different from what we have in state
      // — which can happen when the upload route persisted the URL but the
      // subsequent full-save was cancelled by navigation.
      // We never overwrite a real (non-blob) URL in state with a null from DB
      // to avoid flashing the upload area while a fresh refetch is in flight.
      const latestStd = latestValuesRef.current.saveTheDatePhotoUrl;
      const latestDig = latestValuesRef.current.digitalInvitationPhotoUrl;

      const stdFromDb = customization.saveTheDatePhotoUrl;
      const digFromDb = customization.digitalInvitationPhotoUrl;

      // Apply DB URL when: our state is empty/blob AND db has a real URL
      if (stdFromDb && (!latestStd || latestStd.startsWith("blob:"))) {
        skipNextAutoSave.current = true;
        setSaveTheDatePhotoUrl(stdFromDb);
        if (customization.saveTheDatePhotoPosition) {
          setSaveTheDatePhotoPosition(customization.saveTheDatePhotoPosition);
        }
      }
      if (digFromDb && (!latestDig || latestDig.startsWith("blob:"))) {
        skipNextAutoSave.current = true;
        setDigitalInvitationPhotoUrl(digFromDb);
        if (customization.digitalInvitationPhotoPosition) {
          setDigitalInvitationPhotoPosition(
            customization.digitalInvitationPhotoPosition,
          );
        }
      }
    }
  }, [customization]);

  // ── Load messages from wedding profile ────────────────────────────────────
  useEffect(() => {
    if (weddingProfile) {
      const couple = [weddingProfile.partner1Name, weddingProfile.partner2Name]
        .filter(Boolean)
        .join(" & ");
      setSaveTheDateMessage(
        weddingProfile.saveTheDateMessage ||
          (couple
            ? `Mark your calendar! ${couple} are getting married and we'd love to celebrate with you. Formal invitation to follow.`
            : "Mark your calendar! We're getting married and we'd love to celebrate with you. Formal invitation to follow."),
      );
      setInvitationMessage(
        weddingProfile.invitationMessage ||
          (couple
            ? `Together with their families, ${couple} joyfully invite you to celebrate their wedding day with them.`
            : "Together with their families, we joyfully invite you to celebrate our wedding day with us."),
      );
    }
  }, [weddingProfile]);

  // ── Photo upload mutation ─────────────────────────────────────────────────
  const uploadPhotoMutation = useMutation({
    mutationFn: async ({
      file,
      type,
    }: {
      file: File;
      type: "save-the-date" | "digital-invitation";
    }) => {
      if (!profileId) throw new Error("Profile ID required");
      const formData = new FormData();
      formData.append("file", file);
      const token = await getToken();
      if (token) tokenRef.current = token;
      const params = new URLSearchParams({
        type,
        profileId: String(profileId),
      });
      const r = await authFetch(
        `/api/invitation-customizations/upload?${params}`,
        {
          method: "POST",
          headers: { ...(token ? { Authorization: `Bearer ${token}` } : {}) },
          body: formData,
        },
      );
      if (!r.ok) {
        const error = await r.json().catch(() => ({ error: "Unknown error" }));
        throw new Error(error.error || `Upload failed with status ${r.status}`);
      }
      return r.json() as Promise<{ url: string }>;
    },
    onSuccess: (data, variables) => {
      if (variables.type === "save-the-date") {
        if (saveTheDateBlobUrlRef.current) {
          URL.revokeObjectURL(saveTheDateBlobUrlRef.current);
          saveTheDateBlobUrlRef.current = null;
        }
        // Update the ref immediately so the unmount save (which reads the ref
        // synchronously) sees the real URL even before React re-renders.
        latestValuesRef.current.saveTheDatePhotoUrl = data.url;
        latestValuesRef.current.saveTheDatePhotoPosition = { x: 50, y: 50 };
        setSaveTheDatePhotoUrl(data.url);
        setSaveTheDatePhotoPosition({ x: 50, y: 50 });
        setStdTextOverrides((old) =>
          resetPhotoObjectPosition(old, "std:photo"),
        );
        setCustomizationCache((old) =>
          old
            ? {
                ...old,
                saveTheDatePhotoUrl: data.url,
                saveTheDatePhotoPosition: { x: 50, y: 50 },
                textOverrides: resetPhotoObjectPosition(
                  old.textOverrides,
                  "std:photo",
                ),
              }
            : old,
        );
      } else {
        if (digitalInvitationBlobUrlRef.current) {
          URL.revokeObjectURL(digitalInvitationBlobUrlRef.current);
          digitalInvitationBlobUrlRef.current = null;
        }
        // Update the ref immediately so the unmount save (which reads the ref
        // synchronously) sees the real URL even before React re-renders.
        latestValuesRef.current.digitalInvitationPhotoUrl = data.url;
        latestValuesRef.current.digitalInvitationPhotoPosition = {
          x: 50,
          y: 50,
        };
        setDigitalInvitationPhotoUrl(data.url);
        setDigitalInvitationPhotoPosition({ x: 50, y: 50 });
        setDigTextOverrides((old) =>
          resetPhotoObjectPosition(old, "dig:photo"),
        );
        setCustomizationCache((old) =>
          old
            ? {
                ...old,
                digitalInvitationPhotoUrl: data.url,
                digitalInvitationPhotoPosition: { x: 50, y: 50 },
                textOverrides: resetPhotoObjectPosition(
                  old.textOverrides,
                  "dig:photo",
                ),
              }
            : old,
        );
      }

      // Persist the full customization immediately so navigating away before
      // the debounced auto-save fires doesn't lose the uploaded photo URL.
      // Use the server URL for the just-uploaded photo; strip any blob URLs
      // for the other photo slot (upload still in-flight) so we don't
      // overwrite an already-persisted value in the DB.
      // Use keepalive so the request survives same-page navigation.
      skipNextAutoSave.current = true;
      const isSaveTheDate = variables.type === "save-the-date";
      const stdUrl = isSaveTheDate ? data.url : saveTheDatePhotoUrl;
      const digUrl = !isSaveTheDate ? data.url : digitalInvitationPhotoUrl;
      const payload: Record<string, unknown> = buildPayload(stdUrl, digUrl);
      if (
        typeof payload.saveTheDatePhotoUrl === "string" &&
        payload.saveTheDatePhotoUrl.startsWith("blob:")
      ) {
        delete payload.saveTheDatePhotoUrl;
      }
      if (
        typeof payload.digitalInvitationPhotoUrl === "string" &&
        payload.digitalInvitationPhotoUrl.startsWith("blob:")
      ) {
        delete payload.digitalInvitationPhotoUrl;
      }
      const apiBase = (import.meta.env.VITE_API_URL ?? "").replace(/\/+$/, "");
      const cachedToken = tokenRef.current;
      fetch(`${apiBase}/api/invitation-customizations`, {
        method: "POST",
        keepalive: true,
        credentials: "include",
        headers: {
          "Content-Type": "application/json",
          ...(cachedToken ? { Authorization: `Bearer ${cachedToken}` } : {}),
        },
        body: JSON.stringify(payload),
      }).catch((err) => {
        console.error(
          "[InvitationCustomization] post-upload save failed:",
          err,
        );
      });
    },
    onError: (error) => {
      toast({
        title: "Upload Failed",
        description:
          error instanceof Error ? error.message : "Failed to upload photo",
        variant: "destructive",
      });
    },
  });

  // ── Photo selection handlers ──────────────────────────────────────────────
  const handleSaveTheDatePhotoSelected = (file: File | null) => {
    if (saveTheDateBlobUrlRef.current) {
      URL.revokeObjectURL(saveTheDateBlobUrlRef.current);
      saveTheDateBlobUrlRef.current = null;
    }
    if (!file) {
      setSaveTheDatePhotoUrl(null);
      return;
    }
    setSaveTheDatePhotoPosition({ x: 50, y: 50 });
    const localUrl = URL.createObjectURL(file);
    saveTheDateBlobUrlRef.current = localUrl;
    setSaveTheDatePhotoUrl(localUrl);
    uploadPhotoMutation.mutate({ file, type: "save-the-date" });
  };

  const handleDigitalInvitationPhotoSelected = (file: File | null) => {
    if (digitalInvitationBlobUrlRef.current) {
      URL.revokeObjectURL(digitalInvitationBlobUrlRef.current);
      digitalInvitationBlobUrlRef.current = null;
    }
    if (!file) {
      setDigitalInvitationPhotoUrl(null);
      return;
    }
    setDigitalInvitationPhotoPosition({ x: 50, y: 50 });
    const localUrl = URL.createObjectURL(file);
    digitalInvitationBlobUrlRef.current = localUrl;
    setDigitalInvitationPhotoUrl(localUrl);
    uploadPhotoMutation.mutate({ file, type: "digital-invitation" });
  };

  // ── Save mutation (manual) ────────────────────────────────────────────────
  const saveCustomizationsMutation = useMutation({
    mutationFn: async () => {
      if (!profileId) throw new Error("Profile ID required");

      // Build payload then strip any blob: URLs — they are browser-session-only
      // and must never be written to the database.  Omitting the field (rather
      // than nulling it) leaves the existing DB value untouched so a concurrently
      // completing upload is not overwritten.
      const payload = buildPayload(saveTheDatePhotoUrl, digitalInvitationPhotoUrl);
      const body: Record<string, unknown> = { ...payload };
      if (typeof body.saveTheDatePhotoUrl === "string" && (body.saveTheDatePhotoUrl as string).startsWith("blob:")) {
        delete body.saveTheDatePhotoUrl;
      }
      if (typeof body.digitalInvitationPhotoUrl === "string" && (body.digitalInvitationPhotoUrl as string).startsWith("blob:")) {
        delete body.digitalInvitationPhotoUrl;
      }

      const r = await authedFetch("/api/invitation-customizations", {
        method: "POST",
        body: JSON.stringify(body),
      });
      if (!r.ok) {
        const errBody = await r.json().catch(() => ({ error: "Failed to save" }));
        throw new Error((errBody as { error?: string }).error || "Failed to save");
      }
      return r.json();
    },
    onSuccess: (savedCustomization: InvitationCustomization) => {
      queryClient.setQueryData(
        ["invitation-customizations", profileId],
        savedCustomization,
      );
      toast({
        title: "Saved",
        description: "Your invitation customizations have been saved.",
      });
    },
    onError: (error) => {
      toast({
        title: "Error",
        description: error instanceof Error ? error.message : "Failed to save customizations",
        variant: "destructive",
      });
    },
  });

  // ── Message save + AI generate ───────────────────────────────────────────
  const saveMessage = async (type: "saveTheDate" | "digitalInvitation") => {
    setSavingMessage(true);
    try {
      const body =
        type === "saveTheDate" ? { saveTheDateMessage } : { invitationMessage };
      const r = await authedFetch("/api/profile/invitation-settings", {
        method: "PATCH",
        body: JSON.stringify(body),
      });
      if (!r.ok) throw new Error("Failed to save");
      toast({ title: "Message saved" });
    } catch {
      toast({ title: "Failed to save message", variant: "destructive" });
    } finally {
      setSavingMessage(false);
    }
  };

  const generateStdMessage = async () => {
    setStdGenerating(true);
    try {
      const r = await authedFetch("/api/profile/generate-invitation-message", {
        method: "POST",
        body: JSON.stringify({ details: stdAiDetails }),
      });
      if (!r.ok) throw new Error("Failed");
      const data = await r.json();
      setSaveTheDateMessage((data.message || "").trim());
      setStdAiDetails("");
      setShowStdAiPanel(false);
    } catch {
      toast({ title: "Failed to generate message", variant: "destructive" });
    } finally {
      setStdGenerating(false);
    }
  };

  const generateDigMessage = async () => {
    setDigGenerating(true);
    try {
      const r = await authedFetch("/api/profile/generate-invitation-message", {
        method: "POST",
        body: JSON.stringify({ details: digAiDetails }),
      });
      if (!r.ok) throw new Error("Failed");
      const data = await r.json();
      setInvitationMessage((data.message || "").trim());
      setDigAiDetails("");
      setShowDigAiPanel(false);
    } catch {
      toast({ title: "Failed to generate message", variant: "destructive" });
    } finally {
      setDigGenerating(false);
    }
  };

  // ── Reset to brand colors ──────────────────────────────────────────────────
  const BRAND_PALETTE: ColorPalette = {
    primary: "#D4A017",
    secondary: "#F5C842",
    accent: "#D4A017",
    neutral: "#E8E0D0",
  };
  const handleResetToBrandColors = useCallback(() => {
    setPrimaryColor("#D4A017");
    setAutoGeneratedPalette(BRAND_PALETTE);
    setCustomColors(null);
    setSelectedPalette(null);
    if (previewTab === "saveTheDate") {
      setSaveTheDateBackground("#1E1A2E");
      setStdTextOverrides({});
    } else {
      setDigitalInvitationBackground("#1E1A2E");
      setDigTextOverrides({});
    }
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [previewTab]);

  // ── Build save payload ────────────────────────────────────────────────────
  const buildPayload = (
    stdPhotoUrl = saveTheDatePhotoUrl,
    digPhotoUrl = digitalInvitationPhotoUrl,
  ) => ({
    profileId,
    primaryColor,
    colorPalette: autoGeneratedPalette,
    customColors,
    selectedPalette,
    // Keep the legacy fields for backward compat
    backgroundColor: saveTheDateBackground,
    selectedFont: saveTheDateFont,
    selectedLayout: saveTheDateLayout,
    // Per-design fields
    saveTheDatePhotoUrl: stdPhotoUrl,
    digitalInvitationPhotoUrl: digPhotoUrl,
    saveTheDatePhotoPosition,
    digitalInvitationPhotoPosition,
    saveTheDateFont,
    digitalInvitationFont,
    saveTheDateLayout,
    digitalInvitationLayout,
    saveTheDateBackground,
    digitalInvitationBackground,
    backgroundImageUrl,
    // Merge both sets of overrides back into one object for the DB
    textOverrides: { ...stdTextOverrides, ...digTextOverrides },
    useGeneratedInvitation,
  });

  // ── Auto-save (debounced 1s, skip initial load) ───────────────────────────
  useEffect(() => {
    if (!profileId) return;
    if (skipNextAutoSave.current) {
      skipNextAutoSave.current = false;
      return;
    }
    if (saveTheDatePhotoUrl?.startsWith("blob:")) return;
    if (digitalInvitationPhotoUrl?.startsWith("blob:")) return;

    const timer = setTimeout(async () => {
      try {
        const payload = buildPayload();
        const r = await authedFetch("/api/invitation-customizations", {
          method: "POST",
          body: JSON.stringify(payload),
        });
        if (!r.ok) {
          const error = await r
            .json()
            .catch(() => ({ error: "Unknown error" }));
          console.error("Auto-save failed:", error);
          return;
        }
        // Keep the React Query cache in sync so navigating away and back
        // doesn't reload stale values (staleTime: Infinity).
        queryClient.setQueryData(
          ["invitation-customizations", profileId],
          (old: InvitationCustomization | null | undefined) =>
            old ? { ...old, ...payload } : old,
        );
      } catch (error) {
        console.error("Auto-save error:", error);
      }
    }, 1000);

    return () => clearTimeout(timer);
  }, [
    profileId,
    primaryColor,
    autoGeneratedPalette,
    customColors,
    selectedPalette,
    saveTheDatePhotoUrl,
    saveTheDatePhotoPosition,
    saveTheDateFont,
    saveTheDateLayout,
    saveTheDateBackground,
    stdTextOverrides,
    digitalInvitationPhotoUrl,
    digitalInvitationPhotoPosition,
    digitalInvitationFont,
    digitalInvitationLayout,
    digitalInvitationBackground,
    digTextOverrides,
    backgroundImageUrl,
    useGeneratedInvitation,
  ]);

  if (!profileId)
    return <div className="p-4 text-center">Profile not found</div>;

  const defaultWeddingProfile: WeddingProfileData = {
    id: profileId,
    partner1Name: "Partner 1",
    partner2Name: "Partner 2",
    weddingDate: new Date().toISOString(),
    ceremonyTime: "3:00 PM",
    receptionTime: "5:00 PM",
    venue: "TBD",
    location: "TBD",
  };

  const displayWeddingProfile = weddingProfile || defaultWeddingProfile;
  const displayPalette = customColors
    ? { ...autoGeneratedPalette, ...customColors }
    : autoGeneratedPalette;
  const isSTD = previewTab === "saveTheDate";
  const isRsvp = previewTab === "rsvpPage";

  // ── Photo position adapters ───────────────────────────────────────────────
  // In AI mode, positions are stored in dedicated state.
  // In custom mode, positions live in textOverrides as objectX/objectY.
  const stdPhotoPos = useGeneratedInvitation
    ? saveTheDatePhotoPosition
    : { x: stdTextOverrides["std:photo"]?.objectX ?? 50, y: stdTextOverrides["std:photo"]?.objectY ?? 50 };
  const digPhotoPos = useGeneratedInvitation
    ? digitalInvitationPhotoPosition
    : { x: digTextOverrides["dig:photo"]?.objectX ?? 50, y: digTextOverrides["dig:photo"]?.objectY ?? 50 };

  const handleStdPhotoPositionChange = useCallback((pos: { x: number; y: number }) => {
    if (useGeneratedInvitation) {
      setSaveTheDatePhotoPosition(pos);
    } else {
      setStdTextOverrides((prev) => ({
        ...prev,
        "std:photo": { ...prev["std:photo"], objectX: pos.x, objectY: pos.y },
      }));
    }
  // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [useGeneratedInvitation]);

  const handleDigPhotoPositionChange = useCallback((pos: { x: number; y: number }) => {
    if (useGeneratedInvitation) {
      setDigitalInvitationPhotoPosition(pos);
    } else {
      setDigTextOverrides((prev) => ({
        ...prev,
        "dig:photo": { ...prev["dig:photo"], objectX: pos.x, objectY: pos.y },
      }));
    }
  // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [useGeneratedInvitation]);
  // Scale RsvpPagePreview down when the container is narrower than its fixed 390px width
  const rsvpScale = previewContainerWidth > 0 && previewContainerWidth < 390
    ? previewContainerWidth / 390
    : 1.0;

  return (
    <div className="max-w-7xl mx-auto p-3 sm:p-4 space-y-4 sm:space-y-6">
      <div>
        <h1 className="text-2xl sm:text-3xl font-serif font-bold">
          Invitation Customization
        </h1>
        <p className="text-muted-foreground mt-1 text-sm sm:text-base">
          Customize your Save the Date and RSVP Invitation designs
        </p>
      </div>

      <div className="grid grid-cols-1 lg:grid-cols-3 gap-4 sm:gap-6">
        {/* Left Panel — context-aware controls for the active design */}
        <div className="lg:col-span-1 space-y-4 lg:max-h-[90vh] lg:overflow-y-auto">
          {/* Invitation mode toggle */}
          <Card>
            <CardContent className="p-4 space-y-3">
              <p className="text-sm font-medium">Invitation style</p>
              <div className="grid grid-cols-2 gap-2">
                <button
                  type="button"
                  onClick={() => handleSelectDesignMode(true)}
                  className={`flex flex-col items-center gap-2 rounded-lg border-2 p-3 text-left transition-colors ${
                    useGeneratedInvitation
                      ? "border-primary bg-primary/5"
                      : "border-muted hover:border-muted-foreground/40"
                  }`}
                >
                  <Sparkles
                    className={`h-5 w-5 ${useGeneratedInvitation ? "text-primary" : "text-muted-foreground"}`}
                  />
                  <div>
                    <p
                      className={`text-xs font-semibold leading-tight ${useGeneratedInvitation ? "text-primary" : "text-foreground"}`}
                    >
                      AI generated
                    </p>
                    <p className="text-[11px] text-muted-foreground leading-tight mt-0.5">
                      Use the AI-written email
                    </p>
                  </div>
                </button>
                <button
                  type="button"
                  onClick={() => handleSelectDesignMode(false)}
                  className={`flex flex-col items-center gap-2 rounded-lg border-2 p-3 text-left transition-colors ${
                    !useGeneratedInvitation
                      ? "border-primary bg-primary/5"
                      : "border-muted hover:border-muted-foreground/40"
                  }`}
                >
                  <Paintbrush
                    className={`h-5 w-5 ${!useGeneratedInvitation ? "text-primary" : "text-muted-foreground"}`}
                  />
                  <div>
                    <p
                      className={`text-xs font-semibold leading-tight ${!useGeneratedInvitation ? "text-primary" : "text-foreground"}`}
                    >
                      Custom design
                    </p>
                    <p className="text-[11px] text-muted-foreground leading-tight mt-0.5">
                      Use your styled design
                    </p>
                  </div>
                </button>
              </div>
            </CardContent>
          </Card>

          {/* Photo — shows only the slot for the active design */}
          <PhotoUploadSection
            mode={previewTab}
            onSaveTheDatePhotoChange={handleSaveTheDatePhotoSelected}
            onDigitalInvitationPhotoChange={
              handleDigitalInvitationPhotoSelected
            }
            saveTheDatePreviewUrl={saveTheDatePhotoUrl}
            digitalInvitationPreviewUrl={digitalInvitationPhotoUrl}
            isLoading={
              uploadPhotoMutation.isPending ||
              saveCustomizationsMutation.isPending
            }
            isUploadingPhoto={uploadPhotoMutation.isPending}
            isSavingPhoto={saveCustomizationsMutation.isPending}
            onSavePhoto={() => saveCustomizationsMutation.mutate()}
            saveTheDatePhotoPosition={stdPhotoPos}
            onSaveTheDatePositionChange={handleStdPhotoPositionChange}
            digitalInvitationPhotoPosition={digPhotoPos}
            onDigitalInvitationPositionChange={handleDigPhotoPositionChange}
          />

          {/* Brand-color palette — read-only swatches in AI mode, fully editable in custom mode */}
          <ColorSystemSection
            primaryColor={primaryColor}
            onPrimaryColorChange={setPrimaryColor}
            autoGeneratedPalette={autoGeneratedPalette}
            customColors={customColors}
            onCustomColorsChange={setCustomColors}
            selectedPalette={selectedPalette}
            onPaletteSelect={setSelectedPalette}
            backgroundColor={
              isSTD ? saveTheDateBackground : digitalInvitationBackground
            }
            onBackgroundColorChange={
              isSTD ? setSaveTheDateBackground : setDigitalInvitationBackground
            }
            readOnly={useGeneratedInvitation}
          />

          {/* Layout / background / font — hidden in AI mode and on RSVP Page tab (no layout support) */}
          {!useGeneratedInvitation && !isRsvp && (
            <DesignOptionsSection
              mode={previewTab}
              selectedLayout={
                isSTD ? saveTheDateLayout : digitalInvitationLayout
              }
              onLayoutChange={
                isSTD ? setSaveTheDateLayout : setDigitalInvitationLayout
              }
              backgroundColor={
                isSTD ? saveTheDateBackground : digitalInvitationBackground
              }
              onBackgroundColorChange={
                isSTD
                  ? setSaveTheDateBackground
                  : setDigitalInvitationBackground
              }
              selectedFont={isSTD ? saveTheDateFont : digitalInvitationFont}
              onFontChange={
                isSTD ? setSaveTheDateFont : setDigitalInvitationFont
              }
              colors={displayPalette}
            />
          )}

          {/* Message — AI generator + editable text */}
          <Card>
            <CardContent className="p-4 space-y-3">
              <div className="flex items-center justify-between">
                <p className="text-sm font-medium">
                  {isSTD ? "Save the Date Message" : "Invitation Message"}
                </p>
                <Button
                  type="button"
                  size="sm"
                  variant="outline"
                  className="gap-1.5 text-xs h-7 px-2.5 border-primary/30 text-primary hover:bg-primary/5"
                  onClick={() =>
                    isSTD
                      ? setShowStdAiPanel((v) => !v)
                      : setShowDigAiPanel((v) => !v)
                  }
                >
                  <Sparkles className="h-3 w-3" />
                  AI Generate
                  {(isSTD ? showStdAiPanel : showDigAiPanel) ? (
                    <ChevronUp className="h-3 w-3" />
                  ) : (
                    <ChevronDown className="h-3 w-3" />
                  )}
                </Button>
              </div>

              {isSTD && showStdAiPanel && (
                <div className="rounded-xl border border-primary/20 bg-primary/5 p-3 space-y-2 animate-in fade-in slide-in-from-top-1 duration-150">
                  <Textarea
                    placeholder="e.g. We're having an intimate outdoor ceremony in the mountains, and we want guests to feel the excitement before the formal invite arrives…"
                    value={stdAiDetails}
                    onChange={(e) => setStdAiDetails(e.target.value)}
                    rows={3}
                    className="resize-none text-sm bg-background"
                  />
                  <Button
                    size="sm"
                    className="gap-2 w-full"
                    onClick={generateStdMessage}
                    disabled={stdGenerating || !stdAiDetails.trim()}
                  >
                    {stdGenerating ? (
                      <>
                        <Loader2 className="h-3.5 w-3.5 animate-spin" />{" "}
                        Generating…
                      </>
                    ) : (
                      <>
                        <Sparkles className="h-3.5 w-3.5" /> Generate Message
                      </>
                    )}
                  </Button>
                </div>
              )}

              {!isSTD && showDigAiPanel && (
                <div className="rounded-xl border border-primary/20 bg-primary/5 p-3 space-y-2 animate-in fade-in slide-in-from-top-1 duration-150">
                  <Textarea
                    placeholder="e.g. We're getting married in a garden at sunset, small intimate ceremony with close family and friends…"
                    value={digAiDetails}
                    onChange={(e) => setDigAiDetails(e.target.value)}
                    rows={3}
                    className="resize-none text-sm bg-background"
                  />
                  <Button
                    size="sm"
                    className="gap-2 w-full"
                    onClick={generateDigMessage}
                    disabled={digGenerating || !digAiDetails.trim()}
                  >
                    {digGenerating ? (
                      <>
                        <Loader2 className="h-3.5 w-3.5 animate-spin" />{" "}
                        Generating…
                      </>
                    ) : (
                      <>
                        <Sparkles className="h-3.5 w-3.5" /> Generate Message
                      </>
                    )}
                  </Button>
                </div>
              )}

              <Textarea
                placeholder={
                  isSTD
                    ? "e.g. Mark your calendar! We're getting married…"
                    : "e.g. Together with their families, we joyfully invite you…"
                }
                value={isSTD ? saveTheDateMessage : invitationMessage}
                onChange={(e) =>
                  isSTD
                    ? setSaveTheDateMessage(e.target.value)
                    : setInvitationMessage(e.target.value)
                }
                rows={4}
                maxLength={400}
                className="resize-none text-sm"
              />

              <div className="flex items-center justify-between">
                <button
                  type="button"
                  className="text-xs text-muted-foreground hover:text-foreground transition-colors"
                  onClick={() => {
                    const couple = [
                      displayWeddingProfile.partner1Name,
                      displayWeddingProfile.partner2Name,
                    ]
                      .filter(Boolean)
                      .join(" & ");
                    if (isSTD) {
                      setSaveTheDateMessage(
                        couple
                          ? `Mark your calendar! ${couple} are getting married and we'd love to celebrate with you. Formal invitation to follow.`
                          : "Mark your calendar! We're getting married and we'd love to celebrate with you. Formal invitation to follow.",
                      );
                    } else {
                      setInvitationMessage(
                        couple
                          ? `Together with their families, ${couple} joyfully invite you to celebrate their wedding day with them.`
                          : "Together with their families, we joyfully invite you to celebrate our wedding day with us.",
                      );
                    }
                  }}
                >
                  <RefreshCw className="inline h-3 w-3 mr-1" />
                  Reset to template
                </button>
                <p className="text-xs text-muted-foreground">
                  {(isSTD ? saveTheDateMessage : invitationMessage).length}/400
                </p>
              </div>

              <Button
                size="sm"
                variant="outline"
                className="w-full gap-2"
                onClick={() =>
                  saveMessage(isSTD ? "saveTheDate" : "digitalInvitation")
                }
                disabled={savingMessage}
              >
                {savingMessage ? (
                  <Loader2 className="h-3.5 w-3.5 animate-spin" />
                ) : (
                  <Save className="h-3.5 w-3.5" />
                )}
                {savingMessage ? "Saving…" : "Save Message"}
              </Button>
            </CardContent>
          </Card>
        </div>

        {/* Right Panel — Preview */}
        <div className="lg:col-span-2">
          <Card className="flex flex-col lg:h-[90vh]">
            <div className="border-b p-3 sm:p-4 space-y-3">
              {/* Reset button — clears only the active design's overrides */}
              <div className="flex items-center justify-between gap-2">
                <p className="text-xs text-muted-foreground">
                  Preview — click any element to customise
                </p>
                {!useGeneratedInvitation && (
                  <Button
                    type="button"
                    size="sm"
                    variant="outline"
                    className="h-8 gap-1.5 text-xs"
                    onClick={handleResetToBrandColors}
                    title={`Reset ${isSTD ? "Save the Date" : "RSVP Invitation"} to brand colours`}
                  >
                    <RotateCcw className="h-3.5 w-3.5" />
                    Reset to Default
                  </Button>
                )}
              </div>

              <Tabs
                value={previewTab}
                onValueChange={(value) => setPreviewTab(value as PreviewTab)}
              >
                <TabsList className="grid w-full grid-cols-2">
                  <TabsTrigger value="saveTheDate" className="text-xs sm:text-sm px-1 sm:px-3">
                    <span className="sm:hidden">Save Date</span>
                    <span className="hidden sm:inline">Save the Date</span>
                  </TabsTrigger>
                  <TabsTrigger value="digitalInvitation" className="text-xs sm:text-sm px-1 sm:px-3">
                    <span className="sm:hidden">Invitation</span>
                    <span className="hidden sm:inline">RSVP Invitation</span>
                  </TabsTrigger>
                </TabsList>
              </Tabs>
            </div>

            <div ref={previewContainerRef} className="flex-1 overflow-auto p-3 sm:p-4">
              {isSTD ? (
                useGeneratedInvitation ? (
                  <AiSaveDatePreview
                    profile={{
                      partner1Name: displayWeddingProfile.partner1Name,
                      partner2Name: displayWeddingProfile.partner2Name,
                      weddingDate: displayWeddingProfile.weddingDate,
                      venue: displayWeddingProfile.venue,
                      venueCity: displayWeddingProfile.venueCity,
                      venueState: displayWeddingProfile.venueState,
                      venueZip: displayWeddingProfile.venueZip,
                      ceremonyTime: displayWeddingProfile.ceremonyTime,
                      receptionTime: displayWeddingProfile.receptionTime,
                      saveTheDateMessage:
                        saveTheDateMessage ||
                        weddingProfile?.saveTheDateMessage,
                    }}
                    palette={displayPalette}
                    photoUrl={saveTheDatePhotoUrl}
                    photoPosition={saveTheDatePhotoPosition}
                  />
                ) : (
                  <SaveTheDatePreview
                    ref={saveTheDatePreviewRef}
                    photoUrl={saveTheDatePhotoUrl}
                    weddingDate={displayWeddingProfile.weddingDate}
                    colors={displayPalette}
                    font={saveTheDateFont}
                    layout={saveTheDateLayout}
                    backgroundColor={saveTheDateBackground}
                    partner1Name={displayWeddingProfile.partner1Name}
                    partner2Name={displayWeddingProfile.partner2Name}
                    venueCity={displayWeddingProfile.venueCity}
                    venueState={displayWeddingProfile.venueState}
                    venueZip={displayWeddingProfile.venueZip}
                    message={saveTheDateMessage || undefined}
                    textOverrides={stdTextOverrides}
                    onTextOverridesChange={setStdTextOverrides}
                  />
                )
              ) : (
                <RsvpPagePreview
                  colors={displayPalette}
                  font={useGeneratedInvitation ? null : digitalInvitationFont}
                  backgroundColor={useGeneratedInvitation ? null : digitalInvitationBackground}
                  partner1Name={displayWeddingProfile.partner1Name}
                  partner2Name={displayWeddingProfile.partner2Name}
                  weddingDate={displayWeddingProfile.weddingDate}
                  venue={displayWeddingProfile.venue}
                  photoUrl={digitalInvitationPhotoUrl}
                  photoPosition={digPhotoPos}
                  onPhotoPositionChange={handleDigPhotoPositionChange}
                  guestName={user?.firstName || "Guest Name"}
                  venueAddress={displayWeddingProfile.location}
                  venueCity={displayWeddingProfile.venueCity}
                  venueState={displayWeddingProfile.venueState}
                  venueZip={displayWeddingProfile.venueZip}
                  ceremonyTime={displayWeddingProfile.ceremonyTime}
                  receptionTime={displayWeddingProfile.receptionTime}
                  invitationMessage={invitationMessage || weddingProfile?.invitationMessage}
                  scale={rsvpScale}
                />
              )}
            </div>
          </Card>
        </div>
      </div>
    </div>
  );
}
