import { useState, useEffect, useRef, useCallback } from "react";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { useAuth, useUser } from "@clerk/react";
import { useRoute } from "wouter";
import { useWorkspace } from "@/contexts/WorkspaceContext";
import { authFetch } from "@/lib/authFetch";
import { PhotoUploadSection } from "@/components/InvitationCustomization/PhotoUploadSection";
import { RsvpPagePreview } from "@/components/InvitationCustomization/RsvpPagePreview";
import {
  AiSaveDatePreview,
} from "@/components/InvitationCustomization/AiPreviewComponents";
import { Card, CardContent } from "@/components/ui/card";
import { WEBSITE_THEMES } from "@/lib/websiteThemes";
import { Button } from "@/components/ui/button";
import { useToast } from "@/hooks/use-toast";
import { Tabs, TabsList, TabsTrigger } from "@/components/ui/tabs";
import {
  Loader2,
  Sparkles,
  ChevronDown,
  ChevronUp,
  RefreshCw,
  RotateCcw,
  Save,
} from "lucide-react";
import { Textarea } from "@/components/ui/textarea";
import type {
  InvitationCustomization,
  ColorPalette,
  PreviewTab,
  WeddingProfileData,
} from "@/types/invitations";

interface RouteParams {
  [key: string]: string | undefined;
  profileId?: string;
}

interface InvitationCustomizationProps {
  profileId?: number;
}

export default function InvitationCustomizationPage({
  profileId: propProfileId,
}: InvitationCustomizationProps = {}) {
  const { getToken } = useAuth();
  const { user } = useUser();
  const { toast } = useToast();
  const { activeWorkspace } = useWorkspace();
  const queryClient = useQueryClient();
  const [, params] = useRoute<RouteParams>("/guests/:profileId");

  const profileId =
    propProfileId ||
    (params?.profileId
      ? parseInt(params.profileId)
      : activeWorkspace?.profileId);
  const [previewTab, setPreviewTab] = useState<PreviewTab>("saveTheDate");
  const [designMode, setDesignMode] = useState<"ai" | "custom">("ai");
  const [customDesign, setCustomDesign] = useState<{
    saveTheDate: { backgroundColor: string; accentColor: string; fontFamily: string; fontSize: string; fontColor: string };
    rsvpInvitation: { backgroundColor: string; accentColor: string; fontFamily: string; fontSize: string; fontColor: string };
  }>({
    saveTheDate: { backgroundColor: "#FFFFFF", accentColor: "#D4A017", fontFamily: "Playfair Display", fontSize: "16", fontColor: "#222222" },
    rsvpInvitation: { backgroundColor: "#FFFFFF", accentColor: "#D4A017", fontFamily: "Playfair Display", fontSize: "16", fontColor: "#222222" },
  });

  // ── Shared brand-color state ──────────────────────────────────────────────
  const [primaryColor, setPrimaryColor] = useState("#D4A017");
  const [autoGeneratedPalette, setAutoGeneratedPalette] =
    useState<ColorPalette>({
      primary: "#D4A017",
      secondary: "#F5C842",
      accent: "#D4A017",
      neutral: "#E8E0D0",
    });
  const [customColors, setCustomColors] =
    useState<Partial<ColorPalette> | null>(null);
  const [selectedPalette, setSelectedPalette] = useState<string | null>(null);
  const [backgroundImageUrl, setBackgroundImageUrl] = useState<string | null>(
    null,
  );

  // ── Photos ────────────────────────────────────────────────────────────────
  const [saveTheDatePhotoUrl, setSaveTheDatePhotoUrl] = useState<string | null>(null);
  const [saveTheDatePhotoPosition, setSaveTheDatePhotoPosition] = useState({ x: 50, y: 50 });
  const [digitalInvitationPhotoUrl, setDigitalInvitationPhotoUrl] = useState<string | null>(null);
  const [digitalInvitationPhotoPosition, setDigitalInvitationPhotoPosition] = useState({ x: 50, y: 50 });

  // ── Messages ──────────────────────────────────────────────────────────────
  const [saveTheDateMessage, setSaveTheDateMessage] = useState("");
  const [invitationMessage, setInvitationMessage] = useState("");
  const [showStdAiPanel, setShowStdAiPanel] = useState(false);
  const [stdAiDetails, setStdAiDetails] = useState("");
  const [stdGenerating, setStdGenerating] = useState(false);
  const [showDigAiPanel, setShowDigAiPanel] = useState(false);
  const [digAiDetails, setDigAiDetails] = useState("");
  const [digGenerating, setDigGenerating] = useState(false);
  const [savingMessage, setSavingMessage] = useState(false);

  // ── Misc ──────────────────────────────────────────────────────────────────
  const skipNextAutoSave = useRef(true);
  const hasInitialized = useRef(false);
  const tokenRef = useRef<string | null>(null);
  const latestValuesRef = useRef({
    profileId,
    primaryColor,
    autoGeneratedPalette,
    customColors,
    selectedPalette,
    saveTheDatePhotoUrl,
    saveTheDatePhotoPosition,
    digitalInvitationPhotoUrl,
    digitalInvitationPhotoPosition,
    backgroundImageUrl,
    designMode,
    customDesign,
  });
  const saveTheDateBlobUrlRef = useRef<string | null>(null);
  const digitalInvitationBlobUrlRef = useRef<string | null>(null);
  const previewContainerRef = useRef<HTMLDivElement>(null);
  const [previewContainerWidth, setPreviewContainerWidth] = useState(0);

  useEffect(() => {
    const el = previewContainerRef.current;
    if (!el) return;
    const observer = new ResizeObserver((entries) => {
      setPreviewContainerWidth(entries[0]?.contentRect.width ?? 0);
    });
    observer.observe(el);
    return () => observer.disconnect();
  }, []);

  latestValuesRef.current = {
    profileId,
    primaryColor,
    autoGeneratedPalette,
    customColors,
    selectedPalette,
    saveTheDatePhotoUrl,
    saveTheDatePhotoPosition,
    digitalInvitationPhotoUrl,
    digitalInvitationPhotoPosition,
    backgroundImageUrl,
    designMode,
    customDesign,
  };

  useEffect(() => {
    return () => {
      if (saveTheDateBlobUrlRef.current)
        URL.revokeObjectURL(saveTheDateBlobUrlRef.current);
      if (digitalInvitationBlobUrlRef.current)
        URL.revokeObjectURL(digitalInvitationBlobUrlRef.current);
    };
  }, []);

  useEffect(() => {
    return () => {
      const v = latestValuesRef.current;
      if (!v.profileId) return;
      if (v.saveTheDatePhotoUrl?.startsWith("blob:")) return;
      if (v.digitalInvitationPhotoUrl?.startsWith("blob:")) return;
      const isCustom = v.designMode === "custom";
      const customAccent = isCustom
        ? v.customDesign.saveTheDate.accentColor
        : null;
      const finalCustomColors = customAccent
        ? { ...(v.customColors ?? {}), accent: customAccent, primary: customAccent }
        : v.customColors;
      const body = JSON.stringify({
        profileId: v.profileId,
        primaryColor: v.primaryColor,
        colorPalette: v.autoGeneratedPalette,
        customColors: finalCustomColors,
        selectedPalette: v.selectedPalette,
        saveTheDatePhotoUrl: v.saveTheDatePhotoUrl,
        digitalInvitationPhotoUrl: v.digitalInvitationPhotoUrl,
        saveTheDatePhotoPosition: v.saveTheDatePhotoPosition,
        digitalInvitationPhotoPosition: v.digitalInvitationPhotoPosition,
        backgroundImageUrl: v.backgroundImageUrl,
        useGeneratedInvitation: !isCustom,
        saveTheDateBackground: isCustom ? v.customDesign.saveTheDate.backgroundColor : null,
        digitalInvitationBackground: isCustom ? v.customDesign.rsvpInvitation.backgroundColor : null,
        saveTheDateFont: isCustom ? v.customDesign.saveTheDate.fontFamily : null,
        digitalInvitationFont: isCustom ? v.customDesign.rsvpInvitation.fontFamily : null,
        saveTheDateFontColor: isCustom ? v.customDesign.saveTheDate.fontColor : null,
        digitalInvitationFontColor: isCustom ? v.customDesign.rsvpInvitation.fontColor : null,
        saveTheDateFontSize: isCustom ? v.customDesign.saveTheDate.fontSize : null,
        digitalInvitationFontSize: isCustom ? v.customDesign.rsvpInvitation.fontSize : null,
      });

      const apiBase = (import.meta.env.VITE_API_URL ?? "").replace(/\/+$/, "");
      const saveUrl = `${apiBase}/api/invitation-customizations`;

      const cachedToken = tokenRef.current;
      if (cachedToken) {
        fetch(saveUrl, {
          method: "POST",
          credentials: "include",
          keepalive: true,
          headers: {
            "Content-Type": "application/json",
            Authorization: `Bearer ${cachedToken}`,
          },
          body,
        }).catch(() => {});
      } else if (typeof navigator !== "undefined" && navigator.sendBeacon) {
        try {
          navigator.sendBeacon(
            saveUrl,
            new Blob([body], { type: "application/json" }),
          );
        } catch {
          // ignore — best-effort
        }
      }
    };
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, []);

  const authedFetch = async (url: string, init: RequestInit = {}) => {
    const token = await getToken();
    if (token) tokenRef.current = token;
    return authFetch(url, {
      ...init,
      credentials: "include",
      headers: {
        ...(!(init.body instanceof FormData)
          ? { "Content-Type": "application/json" }
          : {}),
        ...(init.headers ?? {}),
        ...(token ? { Authorization: `Bearer ${token}` } : {}),
      },
    });
  };

  const setCustomizationCache = useCallback(
    (
      updater: (
        old: InvitationCustomization | null | undefined,
      ) => InvitationCustomization | null | undefined,
    ) => {
      if (!profileId) return;
      queryClient.setQueryData(
        ["invitation-customizations", profileId],
        updater,
      );
    },
    [profileId, queryClient],
  );

  // ── Queries ───────────────────────────────────────────────────────────────
  const { data: weddingProfile } = useQuery({
    queryKey: ["wedding-profile", profileId],
    queryFn: async () => {
      if (!profileId) return null;
      const r = await authedFetch(`/api/profile`);
      if (!r.ok) throw new Error("Failed to fetch profile");
      return r.json() as Promise<WeddingProfileData>;
    },
    enabled: !!profileId,
    retry: 1,
  });

  const { data: customization } = useQuery({
    queryKey: ["invitation-customizations", profileId],
    queryFn: async () => {
      if (!profileId) return null;
      const r = await authedFetch(
        `/api/invitation-customizations?profileId=${profileId}`,
      );
      if (!r.ok) throw new Error("Failed to fetch customizations");
      return r.json() as Promise<InvitationCustomization>;
    },
    enabled: !!profileId,
    staleTime: 0,
    refetchOnMount: "always",
    refetchOnWindowFocus: true,
  });

  // ── Load DB data into state ───────────────────────────────────────────────
  useEffect(() => {
    if (!customization) return;

    if (!hasInitialized.current) {
      hasInitialized.current = true;
      skipNextAutoSave.current = true;

      setPrimaryColor(customization.primaryColor);
      setAutoGeneratedPalette(customization.colorPalette);
      setCustomColors(customization.customColors);
      setSelectedPalette(customization.selectedPalette);
      setBackgroundImageUrl(customization.backgroundImageUrl);

      setSaveTheDatePhotoUrl(customization.saveTheDatePhotoUrl);
      setDigitalInvitationPhotoUrl(customization.digitalInvitationPhotoUrl);

      // Restore the per-invitation design mode + custom design fields from
      // the saved record so the toggle and panel reflect what was last saved.
      if (customization.useGeneratedInvitation === false) {
        if (customization.saveTheDateBackground || customization.digitalInvitationBackground) setDesignMode("custom");
      }
      const savedAccent =
        customization.customColors?.accent ??
        customization.colorPalette?.accent ??
        "#D4A017";
      setCustomDesign({
        saveTheDate: {
          backgroundColor: customization.saveTheDateBackground ?? "#FFFFFF",
          accentColor: savedAccent,
          fontFamily: customization.saveTheDateFont ?? "Playfair Display",
          fontSize: customization.saveTheDateFontSize ?? "16",
          fontColor: customization.saveTheDateFontColor ?? "#222222",
        },
        rsvpInvitation: {
          backgroundColor: customization.digitalInvitationBackground ?? "#FFFFFF",
          accentColor: savedAccent,
          fontFamily: customization.digitalInvitationFont ?? "Playfair Display",
          fontSize: customization.digitalInvitationFontSize ?? "16",
          fontColor: customization.digitalInvitationFontColor ?? "#222222",
        },
      });

      if (customization.saveTheDatePhotoPosition) {
        setSaveTheDatePhotoPosition(customization.saveTheDatePhotoPosition);
      }
      if (customization.digitalInvitationPhotoPosition) {
        setDigitalInvitationPhotoPosition(customization.digitalInvitationPhotoPosition);
      }
    } else {
      const latestStd = latestValuesRef.current.saveTheDatePhotoUrl;
      const latestDig = latestValuesRef.current.digitalInvitationPhotoUrl;
      const stdFromDb = customization.saveTheDatePhotoUrl;
      const digFromDb = customization.digitalInvitationPhotoUrl;

      if (stdFromDb && (!latestStd || latestStd.startsWith("blob:"))) {
        skipNextAutoSave.current = true;
        setSaveTheDatePhotoUrl(stdFromDb);
        if (customization.saveTheDatePhotoPosition) {
          setSaveTheDatePhotoPosition(customization.saveTheDatePhotoPosition);
        }
      }
      if (digFromDb && (!latestDig || latestDig.startsWith("blob:"))) {
        skipNextAutoSave.current = true;
        setDigitalInvitationPhotoUrl(digFromDb);
        if (customization.digitalInvitationPhotoPosition) {
          setDigitalInvitationPhotoPosition(customization.digitalInvitationPhotoPosition);
        }
      }
    }
  }, [customization]);

  // ── Load messages from wedding profile ────────────────────────────────────
  useEffect(() => {
    if (weddingProfile) {
      const couple = [weddingProfile.partner1Name, weddingProfile.partner2Name]
        .filter(Boolean)
        .join(" & ");
      setSaveTheDateMessage(
        weddingProfile.saveTheDateMessage ||
          (couple
            ? `Mark your calendar! ${couple} are getting married and we'd love to celebrate with you. Formal invitation to follow.`
            : "Mark your calendar! We're getting married and we'd love to celebrate with you. Formal invitation to follow."),
      );
      setInvitationMessage(
        weddingProfile.invitationMessage ||
          (couple
            ? `Together with their families, ${couple} joyfully invite you to celebrate their wedding day with them.`
            : "Together with their families, we joyfully invite you to celebrate our wedding day with us."),
      );
    }
  }, [weddingProfile]);

  // ── Photo upload mutation ─────────────────────────────────────────────────
  const uploadPhotoMutation = useMutation({
    mutationFn: async ({
      file,
      type,
    }: {
      file: File;
      type: "save-the-date" | "digital-invitation";
    }) => {
      if (!profileId) throw new Error("Profile ID required");
      const formData = new FormData();
      formData.append("file", file);
      const token = await getToken();
      if (token) tokenRef.current = token;
      const params = new URLSearchParams({
        type,
        profileId: String(profileId),
      });
      const r = await authFetch(
        `/api/invitation-customizations/upload?${params}`,
        {
          method: "POST",
          headers: { ...(token ? { Authorization: `Bearer ${token}` } : {}) },
          body: formData,
        },
      );
      if (!r.ok) {
        const error = await r.json().catch(() => ({ error: "Unknown error" }));
        throw new Error(error.error || `Upload failed with status ${r.status}`);
      }
      return r.json() as Promise<{ url: string }>;
    },
    onSuccess: (data, variables) => {
      if (variables.type === "save-the-date") {
        if (saveTheDateBlobUrlRef.current) {
          URL.revokeObjectURL(saveTheDateBlobUrlRef.current);
          saveTheDateBlobUrlRef.current = null;
        }
        latestValuesRef.current.saveTheDatePhotoUrl = data.url;
        latestValuesRef.current.saveTheDatePhotoPosition = { x: 50, y: 50 };
        setSaveTheDatePhotoUrl(data.url);
        setSaveTheDatePhotoPosition({ x: 50, y: 50 });
        setCustomizationCache((old) =>
          old ? { ...old, saveTheDatePhotoUrl: data.url, saveTheDatePhotoPosition: { x: 50, y: 50 } } : old,
        );
      } else {
        if (digitalInvitationBlobUrlRef.current) {
          URL.revokeObjectURL(digitalInvitationBlobUrlRef.current);
          digitalInvitationBlobUrlRef.current = null;
        }
        latestValuesRef.current.digitalInvitationPhotoUrl = data.url;
        latestValuesRef.current.digitalInvitationPhotoPosition = { x: 50, y: 50 };
        setDigitalInvitationPhotoUrl(data.url);
        setDigitalInvitationPhotoPosition({ x: 50, y: 50 });
        setCustomizationCache((old) =>
          old ? { ...old, digitalInvitationPhotoUrl: data.url, digitalInvitationPhotoPosition: { x: 50, y: 50 } } : old,
        );
      }

      skipNextAutoSave.current = true;
      const isSaveTheDate = variables.type === "save-the-date";
      const stdUrl = isSaveTheDate ? data.url : saveTheDatePhotoUrl;
      const digUrl = !isSaveTheDate ? data.url : digitalInvitationPhotoUrl;
      const payload: Record<string, unknown> = buildPayload(stdUrl, digUrl);
      if (typeof payload.saveTheDatePhotoUrl === "string" && payload.saveTheDatePhotoUrl.startsWith("blob:")) {
        delete payload.saveTheDatePhotoUrl;
      }
      if (typeof payload.digitalInvitationPhotoUrl === "string" && payload.digitalInvitationPhotoUrl.startsWith("blob:")) {
        delete payload.digitalInvitationPhotoUrl;
      }
      const apiBase = (import.meta.env.VITE_API_URL ?? "").replace(/\/+$/, "");
      const cachedToken = tokenRef.current;
      fetch(`${apiBase}/api/invitation-customizations`, {
        method: "POST",
        keepalive: true,
        credentials: "include",
        headers: {
          "Content-Type": "application/json",
          ...(cachedToken ? { Authorization: `Bearer ${cachedToken}` } : {}),
        },
        body: JSON.stringify(payload),
      }).catch(() => {});
    },
    onError: (error) => {
      toast({
        title: "Upload Failed",
        description: error instanceof Error ? error.message : "Failed to upload photo",
        variant: "destructive",
      });
    },
  });

  // ── Photo selection handlers ──────────────────────────────────────────────
  const handleSaveTheDatePhotoSelected = (file: File | null) => {
    if (saveTheDateBlobUrlRef.current) {
      URL.revokeObjectURL(saveTheDateBlobUrlRef.current);
      saveTheDateBlobUrlRef.current = null;
    }
    if (!file) { setSaveTheDatePhotoUrl(null); return; }
    setSaveTheDatePhotoPosition({ x: 50, y: 50 });
    const localUrl = URL.createObjectURL(file);
    saveTheDateBlobUrlRef.current = localUrl;
    setSaveTheDatePhotoUrl(localUrl);
    uploadPhotoMutation.mutate({ file, type: "save-the-date" });
  };

  const handleDigitalInvitationPhotoSelected = (file: File | null) => {
    if (digitalInvitationBlobUrlRef.current) {
      URL.revokeObjectURL(digitalInvitationBlobUrlRef.current);
      digitalInvitationBlobUrlRef.current = null;
    }
    if (!file) { setDigitalInvitationPhotoUrl(null); return; }
    setDigitalInvitationPhotoPosition({ x: 50, y: 50 });
    const localUrl = URL.createObjectURL(file);
    digitalInvitationBlobUrlRef.current = localUrl;
    setDigitalInvitationPhotoUrl(localUrl);
    uploadPhotoMutation.mutate({ file, type: "digital-invitation" });
  };

  // ── Save mutation (manual) ────────────────────────────────────────────────
  const saveCustomizationsMutation = useMutation({
    mutationFn: async () => {
      if (!profileId) throw new Error("Profile ID required");
      const payload = buildPayload(saveTheDatePhotoUrl, digitalInvitationPhotoUrl);
      const body: Record<string, unknown> = { ...payload };
      if (typeof body.saveTheDatePhotoUrl === "string" && (body.saveTheDatePhotoUrl as string).startsWith("blob:")) {
        delete body.saveTheDatePhotoUrl;
      }
      if (typeof body.digitalInvitationPhotoUrl === "string" && (body.digitalInvitationPhotoUrl as string).startsWith("blob:")) {
        delete body.digitalInvitationPhotoUrl;
      }
      const r = await authedFetch("/api/invitation-customizations", {
        method: "POST",
        body: JSON.stringify(body),
      });
      if (!r.ok) {
        const errBody = await r.json().catch(() => ({ error: "Failed to save" }));
        throw new Error((errBody as { error?: string }).error || "Failed to save");
      }
      return r.json();
    },
    onSuccess: (savedCustomization: InvitationCustomization) => {
      queryClient.setQueryData(["invitation-customizations", profileId], savedCustomization);
      toast({ title: "Saved", description: "Your invitation customizations have been saved." });
    },
    onError: (error) => {
      toast({
        title: "Error",
        description: error instanceof Error ? error.message : "Failed to save customizations",
        variant: "destructive",
      });
    },
  });

  // ── Message save + AI generate ───────────────────────────────────────────
  const saveMessage = async (type: "saveTheDate" | "digitalInvitation") => {
    setSavingMessage(true);
    try {
      const body = type === "saveTheDate" ? { saveTheDateMessage } : { invitationMessage };
      const r = await authedFetch("/api/profile/invitation-settings", {
        method: "PATCH",
        body: JSON.stringify(body),
      });
      if (!r.ok) throw new Error("Failed to save");
      toast({ title: "Message saved" });
    } catch {
      toast({ title: "Failed to save message", variant: "destructive" });
    } finally {
      setSavingMessage(false);
    }
  };

  const generateStdMessage = async () => {
    setStdGenerating(true);
    try {
      const r = await authedFetch("/api/profile/generate-invitation-message", {
        method: "POST",
        body: JSON.stringify({ details: stdAiDetails }),
      });
      if (!r.ok) throw new Error("Failed");
      const data = await r.json();
      setSaveTheDateMessage((data.message || "").trim());
      setStdAiDetails("");
      setShowStdAiPanel(false);
    } catch {
      toast({ title: "Failed to generate message", variant: "destructive" });
    } finally {
      setStdGenerating(false);
    }
  };

  const generateDigMessage = async () => {
    setDigGenerating(true);
    try {
      const r = await authedFetch("/api/profile/generate-invitation-message", {
        method: "POST",
        body: JSON.stringify({ details: digAiDetails }),
      });
      if (!r.ok) throw new Error("Failed");
      const data = await r.json();
      setInvitationMessage((data.message || "").trim());
      setDigAiDetails("");
      setShowDigAiPanel(false);
    } catch {
      toast({ title: "Failed to generate message", variant: "destructive" });
    } finally {
      setDigGenerating(false);
    }
  };

  // ── Reset colors to brand defaults ───────────────────────────────────────
  const BRAND_PALETTE: ColorPalette = {
    primary: "#D4A017",
    secondary: "#F5C842",
    accent: "#D4A017",
    neutral: "#E8E0D0",
  };
  const handleResetToDefault = useCallback(() => {
    setPrimaryColor("#D4A017");
    setAutoGeneratedPalette(BRAND_PALETTE);
    setCustomColors(null);
    setSelectedPalette(null);
  // eslint-disable-next-line react-hooks/exhaustive-deps
  }, []);

  // ── Build save payload ────────────────────────────────────────────────────
  const buildPayload = (
    stdPhotoUrl = saveTheDatePhotoUrl,
    digPhotoUrl = digitalInvitationPhotoUrl,
  ) => {
    const stdCustom = designMode === "custom";
    const digCustom = designMode === "custom";
    const eitherCustom = designMode === "custom";
    // Custom accent: pick from whichever invitation type is currently in
    // custom mode (prefer STD if both are custom). The accent is shared on
    // the colorPalette / customColors record because the legacy renderer
    // uses one accent across both invitations.
    const customAccent = stdCustom
      ? customDesign.saveTheDate.accentColor
      : digCustom
      ? customDesign.rsvpInvitation.accentColor
      : null;
    const finalCustomColors = customAccent
      ? { ...(customColors ?? {}), accent: customAccent, primary: customAccent }
      : customColors;
    return {
      profileId,
      primaryColor,
      colorPalette: autoGeneratedPalette,
      customColors: finalCustomColors,
      selectedPalette,
      saveTheDatePhotoUrl: stdPhotoUrl,
      digitalInvitationPhotoUrl: digPhotoUrl,
      saveTheDatePhotoPosition,
      digitalInvitationPhotoPosition,
      backgroundImageUrl,
      // useGeneratedInvitation === false the moment EITHER invitation type
      // is in custom mode — that's how the public pages, email, and PDF
      // know to apply the custom design.
      useGeneratedInvitation: !eitherCustom,
      // Per-invitation custom styling. Null when that invitation is in AI
      // mode so the public renderer falls back to AI defaults cleanly.
      saveTheDateBackground: stdCustom ? customDesign.saveTheDate.backgroundColor : null,
      digitalInvitationBackground: digCustom ? customDesign.rsvpInvitation.backgroundColor : null,
      saveTheDateFont: stdCustom ? customDesign.saveTheDate.fontFamily : null,
      digitalInvitationFont: digCustom ? customDesign.rsvpInvitation.fontFamily : null,
      saveTheDateFontColor: stdCustom ? customDesign.saveTheDate.fontColor : null,
      digitalInvitationFontColor: digCustom ? customDesign.rsvpInvitation.fontColor : null,
      saveTheDateFontSize: stdCustom ? customDesign.saveTheDate.fontSize : null,
      digitalInvitationFontSize: digCustom ? customDesign.rsvpInvitation.fontSize : null,
    };
  };

  // ── Load Google Font when a custom font is selected ──────────────────────
  useEffect(() => {
    if (designMode !== "custom") return;
    const fonts = new Set([
      customDesign.saveTheDate.fontFamily,
      customDesign.rsvpInvitation.fontFamily,
    ]);
    fonts.forEach((family) => {
      if (!family) return;
      const id = `gfont-${family.replace(/\s+/g, "-")}`;
      if (document.getElementById(id)) return;
      const link = document.createElement("link");
      link.id = id;
      link.rel = "stylesheet";
      link.href = `https://fonts.googleapis.com/css2?family=${encodeURIComponent(family)}:ital,wght@0,400;0,500;0,600;0,700;1,400&display=swap`;
      document.head.appendChild(link);
    });
  }, [designMode, customDesign.saveTheDate.fontFamily, customDesign.rsvpInvitation.fontFamily]);

  // ── Auto-save (debounced 1s, skip initial load) ───────────────────────────
  useEffect(() => {
    if (!profileId) return;
    if (skipNextAutoSave.current) {
      skipNextAutoSave.current = false;
      return;
    }
    if (saveTheDatePhotoUrl?.startsWith("blob:")) return;
    if (digitalInvitationPhotoUrl?.startsWith("blob:")) return;

    const timer = setTimeout(async () => {
      try {
        const payload = buildPayload();
        const r = await authedFetch("/api/invitation-customizations", {
          method: "POST",
          body: JSON.stringify(payload),
        });
        if (!r.ok) {
          const error = await r.json().catch(() => ({ error: "Unknown error" }));
          console.error("Auto-save failed:", error);
          return;
        }
        queryClient.setQueryData(
          ["invitation-customizations", profileId],
          (old: InvitationCustomization | null | undefined) =>
            old ? { ...old, ...payload } : old,
        );
      } catch (error) {
        console.error("Auto-save error:", error);
      }
    }, 1000);

    return () => clearTimeout(timer);
  }, [
    profileId,
    primaryColor,
    autoGeneratedPalette,
    customColors,
    selectedPalette,
    saveTheDatePhotoUrl,
    saveTheDatePhotoPosition,
    digitalInvitationPhotoUrl,
    digitalInvitationPhotoPosition,
    backgroundImageUrl,
    designMode,
    customDesign,
  ]);

  // Flush any pending position changes to the DB when navigating away so the
  // email always uses the latest photo crop, not a debounce-lagged value.
  useEffect(() => {
    return () => {
      const v = latestValuesRef.current;
      if (!v.profileId) return;
      if (v.saveTheDatePhotoUrl?.startsWith("blob:")) return;
      if (v.digitalInvitationPhotoUrl?.startsWith("blob:")) return;
      const payload = {
        saveTheDatePhotoPosition: v.saveTheDatePhotoPosition,
        digitalInvitationPhotoPosition: v.digitalInvitationPhotoPosition,
      };
      authFetch("/api/invitation-customizations", {
        method: "POST",
        body: JSON.stringify({ ...payload }),
      }).catch(() => {});
    };
  }, []);

  if (!profileId)
    return <div className="p-4 text-center">Profile not found</div>;

  const defaultWeddingProfile: WeddingProfileData = {
    id: profileId,
    partner1Name: "Partner 1",
    partner2Name: "Partner 2",
    weddingDate: new Date().toISOString(),
    ceremonyTime: "3:00 PM",
    receptionTime: "5:00 PM",
    venue: "TBD",
    location: "TBD",
  };

  const displayWeddingProfile = weddingProfile || defaultWeddingProfile;
  const displayPalette = customColors
    ? { ...autoGeneratedPalette, ...customColors }
    : autoGeneratedPalette;
  const isSTD = previewTab === "saveTheDate";

  const rsvpScale = previewContainerWidth > 0 && previewContainerWidth < 390
    ? previewContainerWidth / 390
    : 1.0;

  return (
    <div className="max-w-7xl mx-auto p-3 sm:p-4 space-y-4 sm:space-y-6">
      <div>
        <h1 className="text-2xl sm:text-3xl font-serif font-bold">
          Invitation Customization
        </h1>
        <p className="text-muted-foreground mt-1 text-sm sm:text-base">
          Customize your Save the Date and RSVP Invitation designs
        </p>
      </div>

      <Tabs
        value={designMode}
        onValueChange={(v) => setDesignMode(v as "ai" | "custom")}
      >
        <TabsList className="grid w-full max-w-md grid-cols-2">
          <TabsTrigger
            value="ai"
            className="data-[state=active]:bg-[#D4A017] data-[state=active]:text-white"
          >
            AI Generated
          </TabsTrigger>
          <TabsTrigger
            value="custom"
            className="data-[state=active]:bg-[#D4A017] data-[state=active]:text-white"
          >
            Custom Design
          </TabsTrigger>
        </TabsList>
      </Tabs>

      <div className="grid grid-cols-1 lg:grid-cols-3 gap-4 sm:gap-6">
        {/* Left Panel */}
        <div className="lg:col-span-1 space-y-4 lg:max-h-[90vh] lg:overflow-y-auto">

          {/* Photo */}
          <PhotoUploadSection
            mode={previewTab}
            onSaveTheDatePhotoChange={handleSaveTheDatePhotoSelected}
            onDigitalInvitationPhotoChange={handleDigitalInvitationPhotoSelected}
            saveTheDatePreviewUrl={saveTheDatePhotoUrl}
            digitalInvitationPreviewUrl={digitalInvitationPhotoUrl}
            isLoading={uploadPhotoMutation.isPending || saveCustomizationsMutation.isPending}
            isUploadingPhoto={uploadPhotoMutation.isPending}
            isSavingPhoto={saveCustomizationsMutation.isPending}
            onSavePhoto={() => saveCustomizationsMutation.mutate()}
            saveTheDatePhotoPosition={saveTheDatePhotoPosition}
            onSaveTheDatePositionChange={setSaveTheDatePhotoPosition}
            digitalInvitationPhotoPosition={digitalInvitationPhotoPosition}
            onDigitalInvitationPositionChange={setDigitalInvitationPhotoPosition}
          />

          {/* Message */}
          <Card>
            <CardContent className="p-4 space-y-3">
              <div className="flex items-center justify-between">
                <p className="text-sm font-medium">
                  {isSTD ? "Save the Date Message" : "Invitation Message"}
                </p>
                <Button
                  type="button"
                  size="sm"
                  variant="outline"
                  className="gap-1.5 text-xs h-7 px-2.5 border-primary/30 text-primary hover:bg-primary/5"
                  onClick={() =>
                    isSTD
                      ? setShowStdAiPanel((v) => !v)
                      : setShowDigAiPanel((v) => !v)
                  }
                >
                  <Sparkles className="h-3 w-3" />
                  AI Generate
                  {(isSTD ? showStdAiPanel : showDigAiPanel) ? (
                    <ChevronUp className="h-3 w-3" />
                  ) : (
                    <ChevronDown className="h-3 w-3" />
                  )}
                </Button>
              </div>

              {isSTD && showStdAiPanel && (
                <div className="rounded-xl border border-primary/20 bg-primary/5 p-3 space-y-2 animate-in fade-in slide-in-from-top-1 duration-150">
                  <Textarea
                    placeholder="e.g. We're having an intimate outdoor ceremony in the mountains…"
                    value={stdAiDetails}
                    onChange={(e) => setStdAiDetails(e.target.value)}
                    rows={3}
                    className="resize-none text-sm bg-background"
                  />
                  <Button
                    size="sm"
                    className="gap-2 w-full"
                    onClick={generateStdMessage}
                    disabled={stdGenerating || !stdAiDetails.trim()}
                  >
                    {stdGenerating ? (
                      <><Loader2 className="h-3.5 w-3.5 animate-spin" /> Generating…</>
                    ) : (
                      <><Sparkles className="h-3.5 w-3.5" /> Generate Message</>
                    )}
                  </Button>
                </div>
              )}

              {!isSTD && showDigAiPanel && (
                <div className="rounded-xl border border-primary/20 bg-primary/5 p-3 space-y-2 animate-in fade-in slide-in-from-top-1 duration-150">
                  <Textarea
                    placeholder="e.g. We're getting married in a garden at sunset…"
                    value={digAiDetails}
                    onChange={(e) => setDigAiDetails(e.target.value)}
                    rows={3}
                    className="resize-none text-sm bg-background"
                  />
                  <Button
                    size="sm"
                    className="gap-2 w-full"
                    onClick={generateDigMessage}
                    disabled={digGenerating || !digAiDetails.trim()}
                  >
                    {digGenerating ? (
                      <><Loader2 className="h-3.5 w-3.5 animate-spin" /> Generating…</>
                    ) : (
                      <><Sparkles className="h-3.5 w-3.5" /> Generate Message</>
                    )}
                  </Button>
                </div>
              )}

              <Textarea
                placeholder={
                  isSTD
                    ? "e.g. Mark your calendar! We're getting married…"
                    : "e.g. Together with their families, we joyfully invite you…"
                }
                value={isSTD ? saveTheDateMessage : invitationMessage}
                onChange={(e) =>
                  isSTD
                    ? setSaveTheDateMessage(e.target.value)
                    : setInvitationMessage(e.target.value)
                }
                rows={4}
                maxLength={400}
                className="resize-none text-sm"
              />

              <div className="flex items-center justify-between">
                <button
                  type="button"
                  className="text-xs text-muted-foreground hover:text-foreground transition-colors"
                  onClick={() => {
                    const couple = [
                      displayWeddingProfile.partner1Name,
                      displayWeddingProfile.partner2Name,
                    ]
                      .filter(Boolean)
                      .join(" & ");
                    if (isSTD) {
                      setSaveTheDateMessage(
                        couple
                          ? `Mark your calendar! ${couple} are getting married and we'd love to celebrate with you. Formal invitation to follow.`
                          : "Mark your calendar! We're getting married and we'd love to celebrate with you. Formal invitation to follow.",
                      );
                    } else {
                      setInvitationMessage(
                        couple
                          ? `Together with their families, ${couple} joyfully invite you to celebrate their wedding day with them.`
                          : "Together with their families, we joyfully invite you to celebrate our wedding day with us.",
                      );
                    }
                  }}
                >
                  <RefreshCw className="inline h-3 w-3 mr-1" />
                  Reset to template
                </button>
                <p className="text-xs text-muted-foreground">
                  {(isSTD ? saveTheDateMessage : invitationMessage).length}/400
                </p>
              </div>

              <Button
                size="sm"
                variant="outline"
                className="w-full gap-2"
                onClick={() => saveMessage(isSTD ? "saveTheDate" : "digitalInvitation")}
                disabled={savingMessage}
              >
                {savingMessage ? (
                  <Loader2 className="h-3.5 w-3.5 animate-spin" />
                ) : (
                  <Save className="h-3.5 w-3.5" />
                )}
                {savingMessage ? "Saving…" : "Save Message"}
              </Button>
            </CardContent>
          </Card>

          {/* Custom Design controls — only render when this invitation's mode is "custom".
              These values are NOT applied to the preview/email/PDF yet. */}
          {(() => {
            const activeKey: "saveTheDate" | "rsvpInvitation" =
              previewTab === "saveTheDate" ? "saveTheDate" : "rsvpInvitation";
            if (designMode !== "custom") return null;
            const fields = customDesign[activeKey];
            const updateField = (field: keyof typeof fields, value: string) => {
              setCustomDesign((prev) => ({
                ...prev,
                [activeKey]: { ...prev[activeKey], [field]: value },
              }));
            };
            const isThemeActive = (themeId: string) => {
              const t = WEBSITE_THEMES.find((x) => x.id === themeId);
              if (!t) return false;
              return (
                fields.backgroundColor.toLowerCase() === t.background.toLowerCase() &&
                fields.accentColor.toLowerCase() === t.primary.toLowerCase() &&
                fields.fontColor.toLowerCase() === t.text.toLowerCase() &&
                fields.fontFamily === t.font
              );
            };
            return (
              <Card>
                <CardContent className="p-4 space-y-3">
                  <p className="text-sm font-medium">Custom Design</p>

                  {/* Theme presets — same swatches as the website editor.
                      Clicking one populates the colour + font fields below
                      so the Save the Date / RSVP invitation can match the
                      wedding website at a tap. */}
                  <div className="space-y-2">
                    <p className="text-xs text-muted-foreground">
                      Quick themes (same as the website editor)
                    </p>
                    <div className="grid grid-cols-2 gap-2">
                      {WEBSITE_THEMES.map((theme) => {
                        const active = isThemeActive(theme.id);
                        return (
                          <button
                            key={theme.id}
                            type="button"
                            onClick={() => {
                              setCustomDesign((prev) => ({
                                ...prev,
                                [activeKey]: {
                                  ...prev[activeKey],
                                  backgroundColor: theme.background,
                                  accentColor: theme.primary,
                                  fontColor: theme.text,
                                  fontFamily: theme.font,
                                },
                              }));
                            }}
                            className={`text-left p-2 rounded-md border transition-all ${
                              active
                                ? "border-primary ring-2 ring-primary/20"
                                : "border-border hover:border-primary/50"
                            }`}
                          >
                            <div className="flex gap-1 mb-1.5">
                              <div className="w-3.5 h-3.5 rounded-full" style={{ background: theme.primary }} />
                              <div className="w-3.5 h-3.5 rounded-full" style={{ background: theme.secondary }} />
                              <div className="w-3.5 h-3.5 rounded-full" style={{ background: theme.neutral }} />
                            </div>
                            <div className="text-[11px] font-medium leading-tight">{theme.name}</div>
                          </button>
                        );
                      })}
                    </div>
                  </div>

                  <div className="grid grid-cols-2 gap-3">
                    <label className="block text-xs space-y-1">
                      <span className="text-muted-foreground">Background</span>
                      <input
                        type="color"
                        value={fields.backgroundColor}
                        onChange={(e) => updateField("backgroundColor", e.target.value)}
                        className="block h-8 w-full rounded border border-input cursor-pointer"
                      />
                    </label>
                    <label className="block text-xs space-y-1">
                      <span className="text-muted-foreground">Accent</span>
                      <input
                        type="color"
                        value={fields.accentColor}
                        onChange={(e) => updateField("accentColor", e.target.value)}
                        className="block h-8 w-full rounded border border-input cursor-pointer"
                      />
                    </label>
                    <label className="block text-xs space-y-1">
                      <span className="text-muted-foreground">Font color</span>
                      <input
                        type="color"
                        value={fields.fontColor}
                        onChange={(e) => updateField("fontColor", e.target.value)}
                        className="block h-8 w-full rounded border border-input cursor-pointer"
                      />
                    </label>
                    <label className="block text-xs space-y-1">
                      <span className="text-muted-foreground">Font size (px)</span>
                      <input
                        type="number"
                        min={8}
                        max={72}
                        value={fields.fontSize}
                        onChange={(e) => updateField("fontSize", e.target.value)}
                        className="block h-8 w-full rounded-md border border-input bg-background px-2 text-sm"
                      />
                    </label>
                  </div>
                  <label className="block text-xs space-y-1">
                    <span className="text-muted-foreground">Font family</span>
                    <select
                      value={fields.fontFamily}
                      onChange={(e) => updateField("fontFamily", e.target.value)}
                      className="block h-8 w-full rounded-md border border-input bg-background px-2 text-sm"
                    >
                      <option value="Playfair Display">Playfair Display</option>
                      <option value="Cormorant Garamond">Cormorant Garamond</option>
                      <option value="Lora">Lora</option>
                      <option value="Cinzel">Cinzel</option>
                      <option value="Great Vibes">Great Vibes</option>
                      <option value="Tangerine">Tangerine</option>
                      <option value="Inter">Inter</option>
                      <option value="Montserrat">Montserrat</option>
                    </select>
                  </label>
                </CardContent>
              </Card>
            );
          })()}
        </div>

        {/* Right Panel — Preview */}
        <div className="lg:col-span-2">
          <Card className="flex flex-col lg:h-[90vh]">
            <div className="border-b p-3 sm:p-4 space-y-3">
              <p className="text-xs text-muted-foreground">Preview</p>
              <Tabs
                value={previewTab}
                onValueChange={(value) => setPreviewTab(value as PreviewTab)}
              >
                <TabsList className="grid w-full grid-cols-2">
                  <TabsTrigger value="saveTheDate" className="text-xs sm:text-sm px-1 sm:px-3">
                    <span className="sm:hidden">Save Date</span>
                    <span className="hidden sm:inline">Save the Date</span>
                  </TabsTrigger>
                  <TabsTrigger value="digitalInvitation" className="text-xs sm:text-sm px-1 sm:px-3">
                    <span className="sm:hidden">Invitation</span>
                    <span className="hidden sm:inline">RSVP Invitation</span>
                  </TabsTrigger>
                </TabsList>
              </Tabs>
            </div>

            <div ref={previewContainerRef} className="flex-1 overflow-auto p-3 sm:p-4">
              {(() => {
                // Same AI layout in both modes. In "custom" mode we only swap
                // colors/font/size by feeding the existing palette/font/backgroundColor
                // props and wrapping in a styled div for inheritable typography.
                const activeMode = designMode;
                const cd = isSTD ? customDesign.saveTheDate : customDesign.rsvpInvitation;
                const isCustom = activeMode === "custom";
                const customPalette = isCustom
                  ? { ...displayPalette, primary: cd.accentColor, secondary: cd.accentColor, accent: cd.accentColor }
                  : displayPalette;
                // Build the CustomColors object so the card shell (bg, dots,
                // borders) actually picks up the chosen theme colors instead
                // of always rendering the hardcoded dark-navy defaults.
                const previewCustomColors = isCustom
                  ? {
                      bg: cd.backgroundColor,
                      accent: cd.accentColor,
                      text: cd.fontColor,
                      muted: cd.fontColor + "99",
                      cardBdr: cd.accentColor + "33",
                      font: cd.fontFamily,
                      fontSize: cd.fontSize,
                    }
                  : undefined;
                return (
                  <div>
                    {isSTD ? (
                      <AiSaveDatePreview
                        profile={{
                          partner1Name: displayWeddingProfile.partner1Name,
                          partner2Name: displayWeddingProfile.partner2Name,
                          weddingDate: displayWeddingProfile.weddingDate,
                          venue: displayWeddingProfile.venue,
                          venueCity: displayWeddingProfile.venueCity,
                          venueState: displayWeddingProfile.venueState,
                          venueZip: displayWeddingProfile.venueZip,
                          ceremonyTime: displayWeddingProfile.ceremonyTime,
                          receptionTime: displayWeddingProfile.receptionTime,
                          saveTheDateMessage: saveTheDateMessage || weddingProfile?.saveTheDateMessage,
                        }}
                        palette={customPalette}
                        photoUrl={saveTheDatePhotoUrl}
                        photoPosition={saveTheDatePhotoPosition}
                        customColors={previewCustomColors}
                      />
                    ) : (
                      <RsvpPagePreview
                        colors={
                          isCustom
                            ? { ...customPalette, accent: cd.accentColor, primary: cd.accentColor }
                            : displayPalette
                        }
                        font={isCustom ? cd.fontFamily : null}
                        backgroundColor={isCustom ? cd.backgroundColor : null}
                        fontColor={isCustom ? cd.fontColor : null}
                        fontSize={isCustom ? cd.fontSize : null}
                        coupleColor={isCustom ? undefined : "#D4A017"}
                        partner1Name={displayWeddingProfile.partner1Name}
                        partner2Name={displayWeddingProfile.partner2Name}
                        weddingDate={displayWeddingProfile.weddingDate}
                        venue={displayWeddingProfile.venue}
                        photoUrl={digitalInvitationPhotoUrl}
                        photoPosition={digitalInvitationPhotoPosition}
                        onPhotoPositionChange={setDigitalInvitationPhotoPosition}
                        guestName={user?.firstName || "Guest Name"}
                        venueAddress={displayWeddingProfile.location}
                        venueCity={displayWeddingProfile.venueCity}
                        venueState={displayWeddingProfile.venueState}
                        venueZip={displayWeddingProfile.venueZip}
                        ceremonyTime={displayWeddingProfile.ceremonyTime}
                        receptionTime={displayWeddingProfile.receptionTime}
                        invitationMessage={invitationMessage || weddingProfile?.invitationMessage}
                        scale={rsvpScale}
                      />
                    )}
                  </div>
                );
              })()}
            </div>
          </Card>
        </div>
      </div>
    </div>
  );
}
