import pino from "pino";

const isProduction = process.env.NODE_ENV === "production";

export const logger = pino({
  level: process.env.LOG_LEVEL ?? "info",
  redact: {
    censor: "[Redacted]",
    paths: [
      "req.headers.authorization",
      "req.headers.cookie",
      "req.headers['clerk-secret-key']",
      "req.headers['x-site-password']",
      "req.headers['x-api-key']",
      "req.headers['svix-signature']",
      "req.headers['svix-id']",
      "req.headers['svix-timestamp']",
      "req.query.password",
      "req.query.token",
      "req.query.inviteToken",
      "req.query.threadToken",
      "req.query.inboundToken",
      "req.body.password",
      "req.body.currentPassword",
      "req.body.newPassword",
      "req.body.token",
      "req.body.ticket",
      "req.body.inviteToken",
      "req.body.threadToken",
      "req.body.inboundToken",
      "req.body.rsvpToken",
      "req.body.guestCollectionToken",
      "res.headers['set-cookie']",
      "body.password",
      "body.currentPassword",
      "body.newPassword",
      "body.token",
      "body.ticket",
      "body.inviteToken",
      "body.threadToken",
      "body.inboundToken",
      "body.rsvpToken",
      "body.guestCollectionToken",
      "password",
      "currentPassword",
      "newPassword",
      "secret",
      "token",
      "ticket",
      "apiKey",
      "authorization",
      "cookie",
      "setCookie",
      "inboundToken",
      "threadToken",
      "inviteToken",
      "rsvpToken",
      "guestCollectionToken",
    ],
  },
  ...(isProduction
    ? {}
    : {
        transport: {
          target: "pino-pretty",
          options: { colorize: true },
        },
      }),
});
