import { Router, type IRouter } from "express";
import healthRouter from "./health";
import profileRouter from "./wedding/profile";
import timelineRouter from "./wedding/timeline";
import vendorRouter from "./wedding/vendor";
import vendorSyncRouter from "./wedding/vendorSync";
import budgetRouter from "./wedding/budget";
import manualExpensesRouter from "./wedding/manualExpenses";
import checklistRouter from "./wedding/checklist";
import dayofRouter from "./wedding/dayof";
import dashboardRouter from "./wedding/dashboard";
import storageRouter from "./storage";
import pdfRouter from "./pdf";
import adminRouter from "./admin";
import collaboratorsRouter from "./collaborators";
import workspaceRouter from "./workspace";
import supportRouter from "./support";
import ariaRouter from "./aria";
import helpRouter from "./help";
import seatingRouter from "./seating";
import guestsRouter from "./guests";
import hotelsRouter from "./wedding/hotels";
import weddingPartyRouter from "./wedding/weddingParty";
import contractsRouter from "./contracts";
import accountRouter from "./account";
import guestCollectRouter from "./guestCollect";
import messagingRouter from "./wedding/messaging";
import ttsRouter from "./tts";

const router: IRouter = Router();

router.use(healthRouter);
router.use(profileRouter);
router.use(timelineRouter);
router.use(vendorRouter);
router.use(vendorSyncRouter);
router.use(budgetRouter);
router.use(manualExpensesRouter);
router.use(checklistRouter);
router.use(dayofRouter);
router.use(dashboardRouter);
router.use(storageRouter);
router.use(pdfRouter);
router.use(adminRouter);
router.use(collaboratorsRouter);
router.use(workspaceRouter);
router.use(supportRouter);
router.use(ariaRouter);
router.use(helpRouter);
router.use(seatingRouter);
router.use(guestsRouter);
router.use(hotelsRouter);
router.use(weddingPartyRouter);
router.use(contractsRouter);
router.use(accountRouter);
router.use(guestCollectRouter);
router.use(messagingRouter);
router.use(ttsRouter);

export default router;
