import { Router } from "express";
import { requireAuth } from "../middlewares/requireAuth";
import { trackEvent } from "../lib/trackEvent";
import type { Response } from "express";
import PDFDocument from "pdfkit";

const router = Router();

const BRAND_PRIMARY = "#7C3F5E";
const BRAND_LIGHT = "#F5EEF2";
const BRAND_MUTED = "#A07090";
const TEXT_DARK = "#1A1A1A";
const TEXT_MEDIUM = "#555555";
const TEXT_LIGHT = "#888888";

function drawHeader(doc: InstanceType<typeof PDFDocument>, subtitle: string) {
  const pageW = doc.page.width;

  doc.rect(0, 0, pageW, 68).fill(BRAND_PRIMARY);

  doc.fillColor("#FFFFFF").font("Helvetica-Bold").fontSize(20).text("A.IDO", 48, 20);
  doc.fillColor("rgba(255,255,255,0.65)").font("Helvetica").fontSize(9)
    .text("AI WEDDING PLANNING OS", 48, 44);

  doc.fillColor("rgba(255,255,255,0.85)").font("Helvetica").fontSize(11)
    .text(subtitle, 0, 26, { align: "right", width: pageW - 48 });

  doc.moveDown(0);
}

function drawFooter(doc: InstanceType<typeof PDFDocument>) {
  const pageW = doc.page.width;
  const pageH = doc.page.height;
  const y = pageH - 40;

  doc.rect(0, y - 10, pageW, 50).fill(BRAND_LIGHT);
  doc.fillColor(BRAND_MUTED).font("Helvetica").fontSize(8)
    .text("Generated by A.IDO — AI Wedding Planning OS  •  aido.app", 0, y + 2, {
      align: "center",
      width: pageW,
    });
}

function finishPdf(doc: InstanceType<typeof PDFDocument>, res: Response, filename: string) {
  res.setHeader("Content-Type", "application/pdf");
  res.setHeader("Content-Disposition", `attachment; filename="${filename}"`);
  doc.pipe(res);
  doc.end();
}

router.post("/pdf/timeline", requireAuth, async (req, res) => {
  try {
    const { events, coupleName, weddingDate, venue } = req.body as {
      events: Array<{ time: string; title: string; description: string; category: string }>;
      coupleName?: string;
      weddingDate?: string;
      venue?: string;
    };

    if (!events || !events.length) {
      return res.status(400).json({ error: "No timeline events provided" });
    }

    const doc = new PDFDocument({ size: "A4", margin: 48, autoFirstPage: true });
    const pageW = doc.page.width;
    const margin = 48;
    const contentW = pageW - margin * 2;

    drawHeader(doc, "Day-Of Timeline");

    doc.y = 88;

    if (coupleName || weddingDate || venue) {
      doc.rect(margin, doc.y, contentW, 42).fill(BRAND_LIGHT).stroke(BRAND_LIGHT);
      doc.fillColor(TEXT_DARK).font("Helvetica-Bold").fontSize(13)
        .text(coupleName ?? "Your Wedding Day", margin + 14, doc.y + 8, { width: contentW - 28 });
      if (weddingDate || venue) {
        doc.fillColor(TEXT_MEDIUM).font("Helvetica").fontSize(9)
          .text([weddingDate, venue].filter(Boolean).join("  •  "), margin + 14, doc.y + 4, {
            width: contentW - 28,
          });
      }
      doc.y += 58;
    }

    doc.moveDown(0.5);

    const categoryColors: Record<string, string> = {
      preparation: "#D4A2B8",
      ceremony: BRAND_PRIMARY,
      cocktail: "#C07A50",
      reception: "#5A6FA0",
      dancing: "#7A5AAA",
      other: TEXT_LIGHT,
    };

    for (let i = 0; i < events.length; i++) {
      const event = events[i];
      const catKey = event.category?.toLowerCase() ?? "other";
      const dotColor = categoryColors[catKey] ?? TEXT_LIGHT;

      const estimatedHeight = 72 + (event.description?.length > 120 ? 30 : 0);
      if (doc.y + estimatedHeight > doc.page.height - 80) {
        doc.addPage();
        drawHeader(doc, "Day-Of Timeline (continued)");
        doc.y = 88;
      }

      const rowY = doc.y;

      doc.circle(margin + 8, rowY + 10, 5).fill(dotColor);

      if (i < events.length - 1) {
        doc.moveTo(margin + 8, rowY + 16).lineTo(margin + 8, rowY + estimatedHeight - 4)
          .stroke("#E8D6E0");
      }

      doc.fillColor(BRAND_PRIMARY).font("Helvetica-Bold").fontSize(10)
        .text(event.time, margin + 22, rowY + 4, { width: 68 });

      const titleX = margin + 98;
      const titleW = contentW - 98 - 60;

      doc.fillColor(TEXT_DARK).font("Helvetica-Bold").fontSize(11)
        .text(event.title, titleX, rowY + 4, { width: titleW });

      const titleHeight = doc.heightOfString(event.title, { width: titleW, font: "Helvetica-Bold", size: 11 });

      doc.fillColor(TEXT_MEDIUM).font("Helvetica").fontSize(9)
        .text(event.description ?? "", titleX, rowY + 6 + titleHeight, {
          width: titleW, lineGap: 2,
        });

      const descHeight = doc.heightOfString(event.description ?? "", {
        width: titleW, font: "Helvetica", size: 9,
      });

      const catLabel = (event.category ?? "").charAt(0).toUpperCase() + (event.category ?? "").slice(1);
      doc.roundedRect(pageW - margin - 56, rowY + 4, 56, 16, 8).fill(dotColor + "22");
      doc.fillColor(dotColor).font("Helvetica").fontSize(7.5)
        .text(catLabel, pageW - margin - 56, rowY + 7, { width: 56, align: "center" });

      doc.y = rowY + Math.max(titleHeight + descHeight + 22, 44);
      doc.moveDown(0.3);
    }

    drawFooter(doc);
    trackEvent(req.userId!, "pdf_exported", { type: "timeline", eventCount: events.length });
    finishPdf(doc, res, "aido-timeline.pdf");
  } catch (err) {
    req.log.error(err, "PDF generation error");
    if (!res.headersSent) {
      res.status(500).json({ error: "Failed to generate PDF" });
    }
  }
});

router.post("/pdf/vendor-email", requireAuth, async (req, res) => {
  try {
    const { subject, body, vendorType, emailType, vendorName } = req.body as {
      subject: string;
      body: string;
      vendorType?: string;
      emailType?: string;
      vendorName?: string;
    };

    if (!subject || !body) {
      return res.status(400).json({ error: "subject and body are required" });
    }

    const doc = new PDFDocument({ size: "A4", margin: 48, autoFirstPage: true });
    const pageW = doc.page.width;
    const margin = 48;
    const contentW = pageW - margin * 2;

    const subtitle = [vendorType, emailType].filter(Boolean).join(" — ") || "Vendor Email Draft";
    drawHeader(doc, subtitle);

    doc.y = 88;

    if (vendorName || vendorType) {
      doc.rect(margin, doc.y, contentW, 36).fill(BRAND_LIGHT);
      doc.fillColor(BRAND_PRIMARY).font("Helvetica-Bold").fontSize(11)
        .text(
          [vendorName ? `To: ${vendorName}` : null, vendorType ? `Type: ${vendorType}` : null, emailType ? `Purpose: ${emailType}` : null]
            .filter(Boolean)
            .join("   •   "),
          margin + 14, doc.y + 12,
          { width: contentW - 28 }
        );
      doc.y += 52;
    }

    doc.moveDown(0.5);

    doc.rect(margin, doc.y, contentW, 1).fill("#E8D6E0");
    doc.moveDown(0.3);

    doc.fillColor(TEXT_LIGHT).font("Helvetica-Bold").fontSize(7.5)
      .text("SUBJECT", margin, doc.y, { characterSpacing: 1.5 });
    doc.moveDown(0.3);
    doc.fillColor(TEXT_DARK).font("Helvetica-Bold").fontSize(14)
      .text(subject, margin, doc.y, { width: contentW, lineGap: 3 });
    doc.moveDown(0.8);

    doc.rect(margin, doc.y, contentW, 1).fill("#E8D6E0");
    doc.moveDown(0.5);

    doc.fillColor(TEXT_LIGHT).font("Helvetica-Bold").fontSize(7.5)
      .text("MESSAGE", margin, doc.y, { characterSpacing: 1.5 });
    doc.moveDown(0.5);

    const paragraphs = body.split(/\n{2,}/);
    for (const para of paragraphs) {
      const lines = para.split(/\n/);
      for (const line of lines) {
        if (doc.y + 20 > doc.page.height - 80) {
          doc.addPage();
          drawHeader(doc, subtitle + " (continued)");
          doc.y = 88;
        }
        doc.fillColor(TEXT_DARK).font("Helvetica").fontSize(11)
          .text(line.trim() || " ", margin, doc.y, { width: contentW, lineGap: 4 });
        doc.moveDown(0.15);
      }
      doc.moveDown(0.6);
    }

    drawFooter(doc);
    trackEvent(req.userId!, "pdf_exported", { type: "vendor_email", vendorType });
    finishPdf(doc, res, "aido-vendor-email.pdf");
  } catch (err) {
    req.log.error(err, "PDF vendor-email generation error");
    if (!res.headersSent) {
      res.status(500).json({ error: "Failed to generate PDF" });
    }
  }
});

export default router;
