import { Router } from "express";
import { requireAuth } from "../middlewares/requireAuth";
import { trackEvent } from "../lib/trackEvent";
import type { Response } from "express";
import PDFDocument from "pdfkit";
import { readFileSync, existsSync } from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const router = Router();

// A.IDO brand palette — matches the warm-gold logged-in portal theme
// (artifacts/aido/src/index.css: --primary: 40 82% 42% + brand gradients)
const BRAND_PRIMARY = "#C38813"; // Warm gold (hsl 40 82% 42%) — matches "Do" in logo
const BRAND_GOLD = "#D4A017";    // Rich gold accent
const BRAND_GOLD_LIGHT = "#F5C842";
const BRAND_PURPLE = "#7B2FBE";  // From brand gradient (pink → purple → blue)
const BRAND_PINK = "#E91E8C";
const BRAND_BLUE = "#4F8EF7";
const BRAND_LIGHT = "#FAF5E8";   // Soft warm cream
const BRAND_RULE = "#E8DCC0";    // Hairline rule color (warm)
const BRAND_MUTED = "#8B6914";   // Muted warm gold/brown for footer text

const TEXT_DARK = "#1A1A1A";
const TEXT_MEDIUM = "#555555";
const TEXT_LIGHT = "#888888";

// Resolve logo path. The build emits to dist/, and assets live alongside the
// artifact root at ../assets/logo.png. Falls back gracefully if not found.
function resolveLogoPath(): string | null {
  const candidates: string[] = [];
  try {
    const here = path.dirname(fileURLToPath(import.meta.url));
    candidates.push(path.resolve(here, "../assets/logo.png"));
    candidates.push(path.resolve(here, "./assets/logo.png"));
  } catch {
    // ignore
  }
  candidates.push(path.resolve(process.cwd(), "assets/logo.png"));
  candidates.push(path.resolve(process.cwd(), "artifacts/api-server/assets/logo.png"));
  for (const p of candidates) {
    if (existsSync(p)) return p;
  }
  return null;
}

let _logoBuffer: Buffer | null | undefined; // undefined = not yet attempted, null = missing
function getLogoBuffer(): Buffer | null {
  if (_logoBuffer !== undefined) return _logoBuffer;
  const p = resolveLogoPath();
  if (!p) {
    _logoBuffer = null;
    return null;
  }
  try {
    _logoBuffer = readFileSync(p);
    return _logoBuffer;
  } catch {
    _logoBuffer = null;
    return null;
  }
}

function drawHeader(doc: InstanceType<typeof PDFDocument>, subtitle: string) {
  const pageW = doc.page.width;
  const headerH = 76;

  // Solid gold header band
  doc.rect(0, 0, pageW, headerH).fill(BRAND_PRIMARY);

  // Thin accent rule along the bottom of the header (gold gradient feel via two stripes)
  doc.rect(0, headerH, pageW, 2).fill(BRAND_GOLD);
  doc.rect(0, headerH + 2, pageW, 1).fill(BRAND_GOLD_LIGHT);

  const logo = getLogoBuffer();
  let textX = 48;
  if (logo) {
    // Embed the real A.IDO logo (44pt square) on the left
    try {
      doc.image(logo, 36, 16, { width: 44, height: 44 });
      textX = 92;
    } catch {
      // If pdfkit can't decode for any reason, fall back to text-only header
      textX = 48;
    }
  }

  doc.fillColor("#FFFFFF").font("Helvetica-Bold").fontSize(20).text("A.IDO", textX, 18);
  doc.fillColor("rgba(255,255,255,0.75)").font("Helvetica").fontSize(8.5)
    .text("AI WEDDING PLANNING OS", textX, 44, { characterSpacing: 1.2 });

  doc.fillColor("rgba(255,255,255,0.92)").font("Helvetica").fontSize(11)
    .text(subtitle, 0, 28, { align: "right", width: pageW - 36 });

  doc.moveDown(0);
}

function drawFooter(doc: InstanceType<typeof PDFDocument>) {
  const pageW = doc.page.width;
  const pageH = doc.page.height;
  const y = pageH - 40;

  doc.rect(0, y - 10, pageW, 50).fill(BRAND_LIGHT);
  // Hairline gold rule above footer
  doc.rect(0, y - 10, pageW, 1).fill(BRAND_GOLD);

  doc.fillColor(BRAND_MUTED).font("Helvetica").fontSize(8)
    .text("Generated by A.IDO — AI Wedding Planning OS  •  aidowedding.net", 0, y + 2, {
      align: "center",
      width: pageW,
    });
}

function finishPdf(doc: InstanceType<typeof PDFDocument>, res: Response, filename: string) {
  res.setHeader("Content-Type", "application/pdf");
  res.setHeader("Content-Disposition", `attachment; filename="${filename}"`);
  doc.pipe(res);
  doc.end();
}

router.post("/pdf/timeline", requireAuth, async (req, res) => {
  try {
    const { events, coupleName, weddingDate, venue } = req.body as {
      events: Array<{ time: string; title: string; description: string; category: string }>;
      coupleName?: string;
      weddingDate?: string;
      venue?: string;
    };

    if (!events || !events.length) {
      return res.status(400).json({ error: "No timeline events provided" });
    }

    const doc = new PDFDocument({ size: "A4", margin: 48, autoFirstPage: true });
    const pageW = doc.page.width;
    const margin = 48;
    const contentW = pageW - margin * 2;

    drawHeader(doc, "Day-Of Timeline");

    doc.y = 96;

    if (coupleName || weddingDate || venue) {
      doc.rect(margin, doc.y, contentW, 46).fill(BRAND_LIGHT);
      // Left gold accent bar
      doc.rect(margin, doc.y, 4, 46).fill(BRAND_GOLD);

      doc.fillColor(TEXT_DARK).font("Helvetica-Bold").fontSize(13)
        .text(coupleName ?? "Your Wedding Day", margin + 16, doc.y + 8, { width: contentW - 28 });
      if (weddingDate || venue) {
        doc.fillColor(BRAND_MUTED).font("Helvetica").fontSize(9)
          .text([weddingDate, venue].filter(Boolean).join("  •  "), margin + 16, doc.y + 4, {
            width: contentW - 28,
          });
      }
      doc.y += 60;
    }

    doc.moveDown(0.5);

    // Brand-aligned category palette (warm gold base + brand gradient accents)
    const categoryColors: Record<string, string> = {
      preparation: "#E8A87C", // peach
      ceremony: BRAND_PRIMARY,
      cocktail: BRAND_GOLD,
      reception: BRAND_PURPLE,
      dancing: BRAND_PINK,
      photos: BRAND_BLUE,
      vendors: "#6B7280",
      travel: "#10B981",
      other: TEXT_LIGHT,
    };

    for (let i = 0; i < events.length; i++) {
      const event = events[i];
      const catKey = event.category?.toLowerCase() ?? "other";
      const dotColor = categoryColors[catKey] ?? TEXT_LIGHT;

      const estimatedHeight = 72 + (event.description?.length > 120 ? 30 : 0);
      if (doc.y + estimatedHeight > doc.page.height - 80) {
        doc.addPage();
        drawHeader(doc, "Day-Of Timeline (continued)");
        doc.y = 96;
      }

      const rowY = doc.y;

      doc.circle(margin + 8, rowY + 10, 5).fill(dotColor);

      if (i < events.length - 1) {
        doc.moveTo(margin + 8, rowY + 16).lineTo(margin + 8, rowY + estimatedHeight - 4)
          .stroke(BRAND_RULE);
      }

      doc.fillColor(BRAND_PRIMARY).font("Helvetica-Bold").fontSize(10)
        .text(event.time, margin + 22, rowY + 4, { width: 68 });

      const titleX = margin + 98;
      const titleW = contentW - 98 - 60;

      doc.fillColor(TEXT_DARK).font("Helvetica-Bold").fontSize(11)
        .text(event.title, titleX, rowY + 4, { width: titleW });

      const titleHeight = doc.heightOfString(event.title, { width: titleW });

      doc.fillColor(TEXT_MEDIUM).font("Helvetica").fontSize(9)
        .text(event.description ?? "", titleX, rowY + 6 + titleHeight, {
          width: titleW, lineGap: 2,
        });

      const descHeight = doc.heightOfString(event.description ?? "", {
        width: titleW,
      });

      const catLabel = (event.category ?? "").charAt(0).toUpperCase() + (event.category ?? "").slice(1);
      doc.roundedRect(pageW - margin - 56, rowY + 4, 56, 16, 8).fill(dotColor + "22");
      doc.fillColor(dotColor).font("Helvetica-Bold").fontSize(7.5)
        .text(catLabel, pageW - margin - 56, rowY + 7, { width: 56, align: "center" });

      doc.y = rowY + Math.max(titleHeight + descHeight + 22, 44);
      doc.moveDown(0.3);
    }

    drawFooter(doc);
    trackEvent(req.userId!, "pdf_exported", { type: "timeline", eventCount: events.length });
    finishPdf(doc, res, "aido-timeline.pdf");
  } catch (err) {
    req.log.error(err, "PDF generation error");
    if (!res.headersSent) {
      res.status(500).json({ error: "Failed to generate PDF" });
    }
  }
});

router.post("/pdf/vendor-email", requireAuth, async (req, res) => {
  try {
    const { subject, body, vendorType, emailType, vendorName } = req.body as {
      subject: string;
      body: string;
      vendorType?: string;
      emailType?: string;
      vendorName?: string;
    };

    if (!subject || !body) {
      return res.status(400).json({ error: "subject and body are required" });
    }

    const doc = new PDFDocument({ size: "A4", margin: 48, autoFirstPage: true });
    const pageW = doc.page.width;
    const margin = 48;
    const contentW = pageW - margin * 2;

    const subtitle = [vendorType, emailType].filter(Boolean).join(" — ") || "Vendor Email Draft";
    drawHeader(doc, subtitle);

    doc.y = 96;

    if (vendorName || vendorType) {
      doc.rect(margin, doc.y, contentW, 38).fill(BRAND_LIGHT);
      doc.rect(margin, doc.y, 4, 38).fill(BRAND_GOLD);
      doc.fillColor(BRAND_PRIMARY).font("Helvetica-Bold").fontSize(11)
        .text(
          [vendorName ? `To: ${vendorName}` : null, vendorType ? `Type: ${vendorType}` : null, emailType ? `Purpose: ${emailType}` : null]
            .filter(Boolean)
            .join("   •   "),
          margin + 16, doc.y + 12,
          { width: contentW - 28 }
        );
      doc.y += 54;
    }

    doc.moveDown(0.5);

    doc.rect(margin, doc.y, contentW, 1).fill(BRAND_RULE);
    doc.moveDown(0.3);

    doc.fillColor(BRAND_MUTED).font("Helvetica-Bold").fontSize(7.5)
      .text("SUBJECT", margin, doc.y, { characterSpacing: 1.5 });
    doc.moveDown(0.3);
    doc.fillColor(TEXT_DARK).font("Helvetica-Bold").fontSize(14)
      .text(subject, margin, doc.y, { width: contentW, lineGap: 3 });
    doc.moveDown(0.8);

    doc.rect(margin, doc.y, contentW, 1).fill(BRAND_RULE);
    doc.moveDown(0.5);

    doc.fillColor(BRAND_MUTED).font("Helvetica-Bold").fontSize(7.5)
      .text("MESSAGE", margin, doc.y, { characterSpacing: 1.5 });
    doc.moveDown(0.5);

    const paragraphs = body.split(/\n{2,}/);
    for (const para of paragraphs) {
      const lines = para.split(/\n/);
      for (const line of lines) {
        if (doc.y + 20 > doc.page.height - 80) {
          doc.addPage();
          drawHeader(doc, subtitle + " (continued)");
          doc.y = 96;
        }
        doc.fillColor(TEXT_DARK).font("Helvetica").fontSize(11)
          .text(line.trim() || " ", margin, doc.y, { width: contentW, lineGap: 4 });
        doc.moveDown(0.15);
      }
      doc.moveDown(0.6);
    }

    drawFooter(doc);
    trackEvent(req.userId!, "pdf_exported", { type: "vendor_email", vendorType });
    finishPdf(doc, res, "aido-vendor-email.pdf");
  } catch (err) {
    req.log.error(err, "PDF vendor-email generation error");
    if (!res.headersSent) {
      res.status(500).json({ error: "Failed to generate PDF" });
    }
  }
});

export default router;
