import { Router } from "express";
import { requireAuth } from "../middlewares/requireAuth";
import { trackEvent } from "../lib/trackEvent";
import type { Response } from "express";
import PDFDocument from "pdfkit";
import { readFileSync, existsSync } from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const router = Router();

// A.IDO brand palette: blush, champagne, soft rose, mauve, and burgundy.
const BRAND_PRIMARY = "#8D294D";
const BRAND_GOLD = "#8D294D";
const BRAND_GOLD_LIGHT = "#E6A6B7";
const BRAND_DARK = "#24171D";
const BRAND_DARK_ALT = "#FFF7F2";
const BRAND_PURPLE = "#B16C8E";
const BRAND_PINK = "#E6A6B7";
const BRAND_BLUE = "#F2E2C6";
const BRAND_LIGHT = "#FFF7F2";
const BRAND_RULE = "#E6A6B7";
const BRAND_MUTED = "#6F3E54";

const TEXT_DARK = "#24171D";
const TEXT_MEDIUM = "#4A3941";
const TEXT_LIGHT = "#8D7480";
const TIMELINE_STATUS_COLORS: Record<string, { fill: string; text: string }> = {
  completed: { fill: "#D1FAE5", text: "#047857" },
  pending: { fill: "#FEF3C7", text: "#B45309" },
  "not started": { fill: "#FEE2E2", text: "#B91C1C" },
  not_started: { fill: "#FEE2E2", text: "#B91C1C" },
};

type PdfDoc = InstanceType<typeof PDFDocument>;

function getTimelineStatusColors(status?: string) {
  return TIMELINE_STATUS_COLORS[(status ?? "").trim().toLowerCase()] ?? {
    fill: "#E2E8F0",
    text: TEXT_MEDIUM,
  };
}

function cleanText(value: unknown, fallback = ""): string {
  return typeof value === "string" ? value.trim() : fallback;
}

function titleCase(value: string): string {
  return value
    .replace(/[_-]+/g, " ")
    .replace(/\s+/g, " ")
    .trim()
    .replace(/\b\w/g, char => char.toUpperCase());
}

function ensurePdfSpace(doc: PdfDoc, neededHeight: number, subtitle: string, topY = 96) {
  if (doc.y + neededHeight <= doc.page.height - 78) return;
  drawFooter(doc);
  doc.addPage();
  drawHeader(doc, subtitle);
  doc.y = topY;
}

// Resolve logo path. The build emits to dist/, and assets live alongside the
// artifact root at ../assets/logo.png. Falls back gracefully if not found.
function resolveLogoPath(): string | null {
  const candidates: string[] = [];
  try {
    const here = path.dirname(fileURLToPath(import.meta.url));
    candidates.push(path.resolve(here, "../assets/logo.png"));
    candidates.push(path.resolve(here, "./assets/logo.png"));
  } catch {
    // ignore
  }
  candidates.push(path.resolve(process.cwd(), "assets/logo.png"));
  candidates.push(path.resolve(process.cwd(), "artifacts/api-server/assets/logo.png"));
  for (const p of candidates) {
    if (existsSync(p)) return p;
  }
  return null;
}

let _logoBuffer: Buffer | null | undefined; // undefined = not yet attempted, null = missing
function getLogoBuffer(): Buffer | null {
  if (_logoBuffer !== undefined) return _logoBuffer;
  const p = resolveLogoPath();
  if (!p) {
    _logoBuffer = null;
    return null;
  }
  try {
    _logoBuffer = readFileSync(p);
    return _logoBuffer;
  } catch {
    _logoBuffer = null;
    return null;
  }
}

function drawHeader(doc: PdfDoc, subtitle: string) {
  const pageW = doc.page.width;
  const headerH = 76;

  // A.IDO header band in the current blush and burgundy brand palette.
  doc.rect(0, 0, pageW, headerH).fill(BRAND_LIGHT);
  doc.rect(0, headerH - 16, pageW, 16).fill("#F9ECE8");

  // Thin accent rule along the bottom of the header.
  doc.rect(0, headerH, pageW, 2).fill(BRAND_GOLD);
  doc.rect(0, headerH + 2, pageW, 1).fill(BRAND_GOLD_LIGHT);

  const logo = getLogoBuffer();
  let textX = 48;
  if (logo) {
    // Embed the real A.IDO logo without distorting its portrait proportions.
    try {
      doc.image(logo, 28, 10, { fit: [58, 56] });
      textX = 94;
    } catch {
      // If pdfkit can't decode for any reason, fall back to text-only header
      textX = 48;
    }
  }

  doc.fillColor(BRAND_PRIMARY).font("Helvetica-Bold").fontSize(20).text("A.IDO", textX, 18);
  doc.fillColor(BRAND_MUTED).font("Helvetica").fontSize(8.5)
    .text("AI WEDDING PLANNING OS", textX, 44, { characterSpacing: 1.2 });

  doc.fillColor(BRAND_MUTED).font("Helvetica").fontSize(11)
    .text(subtitle, 0, 28, { align: "right", width: pageW - 36 });

  doc.moveDown(0);
}

function drawFooter(doc: PdfDoc) {
  const pageW = doc.page.width;
  const pageH = doc.page.height;
  const y = pageH - 40;

  doc.rect(0, y - 10, pageW, 50).fill(BRAND_LIGHT);
  // Hairline gold rule above footer
  doc.rect(0, y - 10, pageW, 1).fill(BRAND_GOLD);

  doc.fillColor(BRAND_MUTED).font("Helvetica").fontSize(8)
    .text("Generated by A.IDO - AI Wedding Planning OS  |  aidowedding.net", 0, y + 2, {
      align: "center",
      width: pageW,
    });
}

function finishPdf(doc: PdfDoc, res: Response, filename: string) {
  res.setHeader("Content-Type", "application/pdf");
  res.setHeader("Content-Disposition", `attachment; filename="${filename}"`);
  doc.pipe(res);
  doc.end();
}

router.post("/pdf/timeline", requireAuth, async (req, res) => {
  try {
    const { events, coupleName, weddingDate, venue } = req.body as {
      events: Array<{
        time?: string;
        title?: string;
        description?: string;
        category?: string;
        status?: string;
        location?: string;
        endTime?: string;
      }>;
      coupleName?: string;
      weddingDate?: string;
      venue?: string;
    };

    if (!events || !events.length) {
      return res.status(400).json({ error: "No timeline events provided" });
    }

    const doc = new PDFDocument({ size: "A4", margin: 48, autoFirstPage: true });
    const pageW = doc.page.width;
    const margin = 48;
    const contentW = pageW - margin * 2;

    drawHeader(doc, "Day-Of Timeline");

    doc.y = 96;

    if (coupleName || weddingDate || venue) {
      const metaY = doc.y;
      doc.rect(margin, metaY, contentW, 50).fill(BRAND_LIGHT);
      // Left gold accent bar
      doc.rect(margin, metaY, 4, 50).fill(BRAND_GOLD);

      doc.fillColor(TEXT_DARK).font("Helvetica-Bold").fontSize(13)
        .text(coupleName ?? "Your Wedding Day", margin + 16, metaY + 8, { width: contentW - 28 });
      if (weddingDate || venue) {
        doc.fillColor(BRAND_MUTED).font("Helvetica").fontSize(9)
          .text([weddingDate, venue].filter(Boolean).join("  |  "), margin + 16, metaY + 30, {
            width: contentW - 28,
          });
      }
      doc.y = metaY + 64;
    }

    doc.moveDown(0.5);

    // Brand-aligned category palette.
    const categoryColors: Record<string, string> = {
      preparation: BRAND_GOLD_LIGHT,
      ceremony: BRAND_PRIMARY,
      cocktail: "#F2E2C6",
      reception: BRAND_PURPLE,
      dancing: BRAND_PINK,
      photos: BRAND_BLUE,
      vendors: "#B16C8E",
      travel: "#6F3E54",
      other: "#C99CAF",
    };

    for (let i = 0; i < events.length; i++) {
      const event = events[i];
      const time = cleanText(event.time, "Time TBD");
      const title = cleanText(event.title, "Untitled timeline item");
      const description = cleanText(event.description);
      const category = cleanText(event.category, "other");
      const status = cleanText(event.status);
      const location = cleanText(event.location);
      const endTime = cleanText(event.endTime);
      const catKey = category.toLowerCase() || "other";
      const dotColor = categoryColors[catKey] ?? TEXT_LIGHT;

      const cardX = margin + 20;
      const cardW = contentW - 20;
      const timeW = 70;
      const badgeW = 80;
      const gap = 14;
      const textX = cardX + 20 + timeW + gap;
      const textW = cardW - 40 - timeW - gap - badgeW - 12;
      const metaParts = [endTime ? `Ends ${endTime}` : "", location].filter(Boolean);
      const titleH = doc.font("Helvetica-Bold").fontSize(11).heightOfString(title, { width: textW, lineGap: 1 });
      const descH = description
        ? doc.font("Helvetica").fontSize(9).heightOfString(description, { width: textW, lineGap: 2 })
        : 0;
      const metaH = metaParts.length
        ? doc.font("Helvetica").fontSize(8.5).heightOfString(metaParts.join("  |  "), { width: textW })
        : 0;
      const textH = titleH + (description ? 6 + descH : 0) + (metaParts.length ? 6 + metaH : 0);
      const cardH = Math.max(66, textH + 26);

      ensurePdfSpace(doc, cardH + 12, "Day-Of Timeline (continued)");

      const rowY = doc.y;

      // Event card using the same light brand surface as the portal.
      doc.roundedRect(cardX, rowY, cardW, cardH, 10).fillAndStroke("#FFFFFF", BRAND_RULE);
      doc.rect(cardX, rowY, 3, cardH).fill(BRAND_GOLD);

      doc.moveTo(margin + 9, rowY - 4).lineTo(margin + 9, rowY + cardH + 10)
        .strokeColor(BRAND_RULE).lineWidth(1).stroke();
      doc.circle(margin + 9, rowY + 18, 5).fill(dotColor);
      doc.circle(margin + 9, rowY + 18, 2.2).fill("#FFFFFF");

      doc.fillColor(BRAND_PRIMARY).font("Helvetica-Bold").fontSize(10)
        .text(time, cardX + 16, rowY + 18, { width: timeW, align: "left" });

      let textY = rowY + 12;
      doc.fillColor(TEXT_DARK).font("Helvetica-Bold").fontSize(11)
        .text(title, textX, textY, { width: textW, lineGap: 1 });
      textY += titleH + 6;
      if (description) {
        doc.fillColor(TEXT_MEDIUM).font("Helvetica").fontSize(9)
          .text(description, textX, textY, { width: textW, lineGap: 2 });
        textY += descH + 6;
      }
      if (metaParts.length) {
        doc.fillColor(TEXT_LIGHT).font("Helvetica").fontSize(8.5)
          .text(metaParts.join("  |  "), textX, textY, { width: textW });
      }

      const badgeX = cardX + cardW - badgeW - 14;
      const catLabel = titleCase(category || "Other");
      doc.roundedRect(badgeX, rowY + 12, badgeW, 17, 8).fill("#F9ECE8");
      doc.fillColor(BRAND_MUTED).font("Helvetica-Bold").fontSize(7.5)
        .text(catLabel, badgeX + 4, rowY + 16, { width: badgeW - 8, align: "center" });

      if (status) {
        const statusColors = getTimelineStatusColors(status);
        doc.roundedRect(badgeX, rowY + 35, badgeW, 17, 8).fill(statusColors.fill);
        doc.fillColor(statusColors.text).font("Helvetica-Bold").fontSize(7.5)
          .text(status, badgeX + 4, rowY + 39, { width: badgeW - 8, align: "center" });
      }

      doc.y = rowY + cardH + 10;
    }

    drawFooter(doc);
    trackEvent(req.userId!, "pdf_exported", { type: "timeline", eventCount: events.length });
    finishPdf(doc, res, "aido-timeline.pdf");
  } catch (err) {
    req.log.error(err, "PDF generation error");
    if (!res.headersSent) {
      res.status(500).json({ error: "Failed to generate PDF" });
    }
  }
});

router.post("/pdf/checklist", requireAuth, async (req, res) => {
  try {
    const { items, coupleName, weddingDate, venue, completedCount, totalCount } = req.body as {
      items: Array<{
        month?: string;
        task?: string;
        description?: string;
        dueDate?: string | null;
        isCompleted?: boolean;
        resolveNote?: string;
      }>;
      coupleName?: string;
      weddingDate?: string;
      venue?: string;
      completedCount?: number;
      totalCount?: number;
    };

    if (!items || !items.length) {
      return res.status(400).json({ error: "No checklist items provided" });
    }

    const doc = new PDFDocument({ size: "A4", margin: 48, autoFirstPage: true });
    const pageW = doc.page.width;
    const margin = 48;
    const contentW = pageW - margin * 2;
    const checkboxX = margin + 12;
    const textX = margin + 44;
    const statusW = 74;
    const textW = contentW - 64 - statusW;

    drawHeader(doc, "Planning Checklist");
    doc.y = 96;

    const metaY = doc.y;
    doc.rect(margin, metaY, contentW, 58).fill(BRAND_LIGHT);
    doc.rect(margin, metaY, 4, 58).fill(BRAND_GOLD);
    doc.fillColor(TEXT_DARK).font("Helvetica-Bold").fontSize(13)
      .text(coupleName || "Your Wedding Checklist", margin + 16, metaY + 9, { width: contentW - 160 });
    doc.fillColor(BRAND_MUTED).font("Helvetica").fontSize(9)
      .text([weddingDate, venue].filter(Boolean).join("  |  "), margin + 16, metaY + 31, { width: contentW - 160 });
    const safeTotal = typeof totalCount === "number" ? totalCount : items.length;
    const safeCompleted = typeof completedCount === "number" ? completedCount : items.filter(item => item.isCompleted).length;
    doc.roundedRect(pageW - margin - 128, metaY + 13, 104, 30, 15).fill("#FFFFFF");
    doc.fillColor(BRAND_PRIMARY).font("Helvetica-Bold").fontSize(12)
      .text(`${safeCompleted}/${safeTotal}`, pageW - margin - 128, metaY + 19, { width: 104, align: "center" });
    doc.fillColor(BRAND_MUTED).font("Helvetica").fontSize(6.8)
      .text("COMPLETED", pageW - margin - 128, metaY + 34, { width: 104, align: "center", characterSpacing: 0.8 });
    doc.y = metaY + 78;

    const grouped = items.reduce<Record<string, typeof items>>((acc, item) => {
      const month = cleanText(item.month, "Checklist");
      if (!acc[month]) acc[month] = [];
      acc[month].push(item);
      return acc;
    }, {});

    for (const [month, monthItems] of Object.entries(grouped)) {
      ensurePdfSpace(doc, 44, "Planning Checklist (continued)");
      const monthY = doc.y;
      doc.fillColor(BRAND_PRIMARY).font("Helvetica-Bold").fontSize(15)
        .text(month, margin, monthY, { width: contentW - 70 });
      doc.roundedRect(pageW - margin - 58, monthY - 1, 58, 18, 9).fill("#F9ECE8");
      const completedInMonth = monthItems.filter(item => item.isCompleted).length;
      doc.fillColor(BRAND_MUTED).font("Helvetica-Bold").fontSize(7.5)
        .text(`${completedInMonth}/${monthItems.length}`, pageW - margin - 58, monthY + 4, { width: 58, align: "center" });
      doc.moveTo(margin, monthY + 24).lineTo(pageW - margin, monthY + 24).strokeColor(BRAND_RULE).lineWidth(1).stroke();
      doc.y = monthY + 34;

      for (const item of monthItems) {
        const task = cleanText(item.task, "Untitled task");
        const description = cleanText(item.description);
        const dueDate = cleanText(item.dueDate ?? "");
        const note = cleanText(item.resolveNote);
        const taskH = doc.font("Helvetica-Bold").fontSize(10.5).heightOfString(task, { width: textW, lineGap: 1 });
        const descH = description
          ? doc.font("Helvetica").fontSize(8.8).heightOfString(description, { width: textW, lineGap: 2 })
          : 0;
        const dueH = dueDate
          ? doc.font("Helvetica-Bold").fontSize(7.8).heightOfString(`Due: ${dueDate}`, { width: textW, lineGap: 1 })
          : 0;
        const noteH = note
          ? doc.font("Helvetica-Oblique").fontSize(8.3).heightOfString(`Note: ${note}`, { width: textW, lineGap: 1 })
          : 0;
        const rowH = Math.max(44, 18 + taskH + (description ? 5 + descH : 0) + (dueDate ? 4 + dueH : 0) + (note ? 6 + noteH : 0));

        ensurePdfSpace(doc, rowH + 8, "Planning Checklist (continued)");
        const rowY = doc.y;
        doc.roundedRect(margin, rowY, contentW, rowH, 9)
          .fillAndStroke(item.isCompleted ? "#F8F3EC" : "#FFFFFF", BRAND_RULE);
        doc.roundedRect(checkboxX, rowY + 14, 13, 13, 3)
          .fillAndStroke(item.isCompleted ? BRAND_PRIMARY : "#FFFFFF", item.isCompleted ? BRAND_PRIMARY : BRAND_RULE);
        if (item.isCompleted) {
          doc.fillColor("#FFFFFF").font("Helvetica-Bold").fontSize(9).text("âœ“", checkboxX + 2.5, rowY + 14.5);
        }

        let textY = rowY + 11;
        doc.fillColor(item.isCompleted ? TEXT_LIGHT : TEXT_DARK).font("Helvetica-Bold").fontSize(10.5)
          .text(task, textX, textY, { width: textW, lineGap: 1 });
        textY += taskH + 5;
        if (description) {
          doc.fillColor(TEXT_MEDIUM).font("Helvetica").fontSize(8.8)
            .text(description, textX, textY, { width: textW, lineGap: 2 });
          textY += descH + 6;
        }
        if (dueDate) {
          doc.fillColor(BRAND_PRIMARY).font("Helvetica-Bold").fontSize(7.8)
            .text(`Due: ${dueDate}`, textX, textY, { width: textW, lineGap: 1 });
          textY += dueH + 6;
        }
        if (note) {
          doc.fillColor(BRAND_MUTED).font("Helvetica-Oblique").fontSize(8.3)
            .text(`Note: ${note}`, textX, textY, { width: textW, lineGap: 1 });
        }

        const statusLabel = item.isCompleted ? "Done" : "Open";
        doc.roundedRect(pageW - margin - statusW - 14, rowY + 12, statusW, 18, 9)
          .fill(item.isCompleted ? "#D1FAE5" : "#F9ECE8");
        doc.fillColor(item.isCompleted ? "#047857" : BRAND_MUTED).font("Helvetica-Bold").fontSize(7.5)
          .text(statusLabel, pageW - margin - statusW - 14, rowY + 16, { width: statusW, align: "center" });

        doc.y = rowY + rowH + 8;
      }

      doc.y += 8;
    }

    drawFooter(doc);
    trackEvent(req.userId!, "pdf_exported", { type: "checklist", itemCount: items.length });
    finishPdf(doc, res, "aido-checklist.pdf");
  } catch (err) {
    req.log.error(err, "PDF checklist generation error");
    if (!res.headersSent) {
      res.status(500).json({ error: "Failed to generate PDF" });
    }
  }
});

router.post("/pdf/vendor-email", requireAuth, async (req, res) => {
  try {
    const { subject, body, vendorType, emailType, vendorName } = req.body as {
      subject: string;
      body: string;
      vendorType?: string;
      emailType?: string;
      vendorName?: string;
    };

    if (!subject || !body) {
      return res.status(400).json({ error: "subject and body are required" });
    }

    const doc = new PDFDocument({ size: "A4", margin: 48, autoFirstPage: true });
    const pageW = doc.page.width;
    const margin = 48;
    const contentW = pageW - margin * 2;

    const subtitle = [vendorType, emailType].filter(Boolean).join(" Ã¢â‚¬â€ ") || "Vendor Email Draft";
    drawHeader(doc, subtitle);

    doc.y = 96;

    if (vendorName || vendorType) {
      doc.rect(margin, doc.y, contentW, 38).fill(BRAND_LIGHT);
      doc.rect(margin, doc.y, 4, 38).fill(BRAND_GOLD);
      doc.fillColor(BRAND_PRIMARY).font("Helvetica-Bold").fontSize(11)
        .text(
          [vendorName ? `To: ${vendorName}` : null, vendorType ? `Type: ${vendorType}` : null, emailType ? `Purpose: ${emailType}` : null]
            .filter(Boolean)
            .join("   Ã¢â‚¬Â¢   "),
          margin + 16, doc.y + 12,
          { width: contentW - 28 }
        );
      doc.y += 54;
    }

    doc.moveDown(0.5);

    doc.rect(margin, doc.y, contentW, 1).fill(BRAND_RULE);
    doc.moveDown(0.3);

    doc.fillColor(BRAND_MUTED).font("Helvetica-Bold").fontSize(7.5)
      .text("SUBJECT", margin, doc.y, { characterSpacing: 1.5 });
    doc.moveDown(0.3);
    doc.fillColor(TEXT_DARK).font("Helvetica-Bold").fontSize(14)
      .text(subject, margin, doc.y, { width: contentW, lineGap: 3 });
    doc.moveDown(0.8);

    doc.rect(margin, doc.y, contentW, 1).fill(BRAND_RULE);
    doc.moveDown(0.5);

    doc.fillColor(BRAND_MUTED).font("Helvetica-Bold").fontSize(7.5)
      .text("MESSAGE", margin, doc.y, { characterSpacing: 1.5 });
    doc.moveDown(0.5);

    const paragraphs = body.split(/\n{2,}/);
    for (const para of paragraphs) {
      const lines = para.split(/\n/);
      for (const line of lines) {
        if (doc.y + 20 > doc.page.height - 80) {
          doc.addPage();
          drawHeader(doc, subtitle + " (continued)");
          doc.y = 96;
        }
        doc.fillColor(TEXT_DARK).font("Helvetica").fontSize(11)
          .text(line.trim() || " ", margin, doc.y, { width: contentW, lineGap: 4 });
        doc.moveDown(0.15);
      }
      doc.moveDown(0.6);
    }

    drawFooter(doc);
    trackEvent(req.userId!, "pdf_exported", { type: "vendor_email", vendorType });
    finishPdf(doc, res, "aido-vendor-email.pdf");
  } catch (err) {
    req.log.error(err, "PDF vendor-email generation error");
    if (!res.headersSent) {
      res.status(500).json({ error: "Failed to generate PDF" });
    }
  }
});

export default router;
