import { useState, useEffect } from "react";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from "@/components/ui/select";
import { ChevronDown } from "lucide-react";
import type { ColorPalette } from "@/types/invitations";

const PRESET_PALETTES = {
  romantic: {
    name: "Romantic",
    description: "Soft pinks, rose golds, and blush tones",
    colors: {
      primary: "#E8A4C4",
      secondary: "#F5D5E3",
      accent: "#D4A017",
      neutral: "#8B7B8F",
    },
    background: "#FFF0F5",
  },
  modern: {
    name: "Modern",
    description: "Sleek grays, silver, and metallics",
    colors: {
      primary: "#333333",
      secondary: "#CCCCCC",
      accent: "#C0C0C0",
      neutral: "#808080",
    },
    background: "#F5F5F5",
  },
  luxury: {
    name: "Luxury",
    description: "Burgundy, champagne gold, and warm taupe",
    colors: {
      primary: "#722F37",
      secondary: "#A4243B",
      accent: "#D4AF37",
      neutral: "#8B7355",
    },
    background: "#1A1014",
  },
  minimalist: {
    name: "Minimalist",
    description: "Clean neutrals, black, and white",
    colors: {
      primary: "#000000",
      secondary: "#FFFFFF",
      accent: "#D3D3D3",
      neutral: "#A9A9A9",
    },
    background: "#FFFFFF",
  },
  seasonal: {
    name: "Seasonal",
    description: "Warm autumn tones with bronze and burgundy",
    colors: {
      primary: "#800020",
      secondary: "#CD853F",
      accent: "#8B4513",
      neutral: "#D2B48C",
    },
    background: "#FAF3E7",
  },
};

interface ColorSystemSectionProps {
  primaryColor: string;
  onPrimaryColorChange: (hex: string) => void;
  autoGeneratedPalette: ColorPalette;
  customColors: Partial<ColorPalette> | null;
  onCustomColorsChange: (colors: Partial<ColorPalette>) => void;
  selectedPalette: string | null;
  onPaletteSelect: (palette: string) => void;
  backgroundColor: string | null;
  onBackgroundColorChange: (hex: string) => void;
  readOnly?: boolean;
}

export function ColorSystemSection({
  primaryColor,
  onPrimaryColorChange,
  autoGeneratedPalette,
  customColors,
  onCustomColorsChange,
  selectedPalette,
  onPaletteSelect,
  backgroundColor,
  onBackgroundColorChange,
  readOnly = false,
}: ColorSystemSectionProps) {
  const [advancedOpen, setAdvancedOpen] = useState(false);
  const [displayPalette, setDisplayPalette] = useState<ColorPalette>(
    autoGeneratedPalette
  );

  useEffect(() => {
    setDisplayPalette(customColors ? { ...autoGeneratedPalette, ...customColors } : autoGeneratedPalette);
  }, [autoGeneratedPalette, customColors]);

  const handleCustomColorChange = (
    key: keyof ColorPalette,
    value: string
  ) => {
    let hex = value;
    if (!hex.startsWith("#")) {
      hex = "#" + hex;
    }
    hex = hex.toUpperCase();

    onCustomColorsChange({
      ...customColors,
      [key]: hex,
    });
    setDisplayPalette({
      ...displayPalette,
      [key]: hex,
    });
  };

  const handlePresetPaletteSelect = (paletteId: string) => {
    const palette =
      PRESET_PALETTES[paletteId as keyof typeof PRESET_PALETTES];
    if (palette) {
      onPaletteSelect(paletteId);
      onPrimaryColorChange(palette.colors.primary);
      onCustomColorsChange(palette.colors);
      setDisplayPalette(palette.colors);
      onBackgroundColorChange(palette.background);
    }
  };

  // ── Read-only mode: palette swatches only (shown in AI generated mode) ──────
  if (readOnly) {
    return (
      <Card>
        <CardHeader>
          <CardTitle className="text-lg">🎨 Color Palette</CardTitle>
        </CardHeader>
        <CardContent>
          <p className="text-xs text-muted-foreground mb-3">
            Your wedding palette — switch to Custom design to edit colors.
          </p>
          <div className="grid grid-cols-2 sm:grid-cols-4 gap-2">
            {(["primary", "secondary", "accent", "neutral"] as const).map((key) => (
              <div key={key} className="space-y-1">
                <div
                  className="w-full h-12 rounded border border-border"
                  style={{ backgroundColor: displayPalette[key] }}
                  title={displayPalette[key]}
                />
                <p className="text-[10px] text-center font-mono truncate">{displayPalette[key]}</p>
                <p className="text-[10px] text-center text-muted-foreground capitalize">{key}</p>
              </div>
            ))}
          </div>
        </CardContent>
      </Card>
    );
  }

  return (
    <Card>
      <CardHeader>
        <CardTitle className="text-lg">🎨 Color System</CardTitle>
      </CardHeader>
      <CardContent className="space-y-6">
        {/* Auto-Generated Palette Display */}
        <div className="space-y-2">
          <label className="text-sm font-medium">Auto-Generated Palette</label>
          <div className="grid grid-cols-2 sm:grid-cols-4 gap-2">
            {(["primary", "secondary", "accent", "neutral"] as const).map(
              (key) => (
                <div key={key} className="space-y-1">
                  <div
                    className="w-full h-16 rounded border border-border cursor-pointer hover:shadow-md transition"
                    style={{ backgroundColor: displayPalette[key] }}
                    title={displayPalette[key]}
                  />
                  <p className="text-xs text-center font-mono">
                    {displayPalette[key]}
                  </p>
                  <p className="text-xs text-center text-muted-foreground capitalize">
                    {key}
                  </p>
                </div>
              )
            )}
          </div>
        </div>

        {/* Advanced Options */}
        <div className="border rounded-lg">
          <button
            onClick={() => setAdvancedOpen(!advancedOpen)}
            className="w-full flex items-center justify-between p-3 hover:bg-muted/50 transition"
          >
            <span className="text-sm font-medium">Advanced Color Options</span>
            <ChevronDown
              className={`h-4 w-4 transition-transform ${
                advancedOpen ? "rotate-180" : ""
              }`}
            />
          </button>

          {advancedOpen && (
            <div className="border-t p-4 space-y-4">
              {/* Pre-made Palettes */}
              <div className="space-y-2">
                <label className="text-sm font-medium">Pre-made Palettes</label>
                <Select value={selectedPalette || ""} onValueChange={handlePresetPaletteSelect}>
                  <SelectTrigger>
                    <SelectValue placeholder="Choose a palette" />
                  </SelectTrigger>
                  <SelectContent>
                    {Object.entries(PRESET_PALETTES).map(([id, palette]) => (
                      <SelectItem key={id} value={id}>
                        {palette.name}
                      </SelectItem>
                    ))}
                  </SelectContent>
                </Select>
                {selectedPalette && (
                  <p className="text-xs text-muted-foreground">
                    {PRESET_PALETTES[selectedPalette as keyof typeof PRESET_PALETTES]?.description}
                  </p>
                )}
              </div>

              {/* Custom Color Inputs */}
              <div className="space-y-2">
                <label className="text-sm font-medium">Custom Colors</label>
                <div className="grid grid-cols-2 gap-3">
                  {(["primary", "secondary", "accent", "neutral"] as const).map(
                    (key) => (
                      <div key={key} className="space-y-1">
                        <label className="text-xs font-medium capitalize">
                          {key}
                        </label>
                        <div className="flex gap-2">
                          <Input
                            type="text"
                            placeholder="#RRGGBB"
                            value={(customColors?.[key] || displayPalette[key]) || ""}
                            onChange={(e) =>
                              handleCustomColorChange(key, e.target.value)
                            }
                            maxLength={7}
                          />
                          <div
                            className="w-10 h-10 rounded border border-border cursor-pointer"
                            style={{
                              backgroundColor:
                                customColors?.[key] || displayPalette[key],
                            }}
                            onClick={() => {
                              const input = document.createElement("input");
                              input.type = "color";
                              input.value = customColors?.[key] || displayPalette[key];
                              input.onchange = (e) => {
                                if (e.target instanceof HTMLInputElement) {
                                  handleCustomColorChange(key, e.target.value);
                                }
                              };
                              input.click();
                            }}
                          />
                        </div>
                      </div>
                    )
                  )}
                </div>
              </div>

              {/* Background Color */}
              <div className="space-y-2">
                <label className="text-sm font-medium">Background Color</label>
                <div className="flex gap-2">
                  <Input
                    type="text"
                    placeholder="#FFFFFF (optional)"
                    value={backgroundColor || ""}
                    onChange={(e) => onBackgroundColorChange(e.target.value)}
                    maxLength={7}
                  />
                  <div
                    className="w-10 h-10 rounded border border-border cursor-pointer"
                    style={{
                      backgroundColor: backgroundColor || "#FFFFFF",
                    }}
                    onClick={() => {
                      const input = document.createElement("input");
                      input.type = "color";
                      input.value = backgroundColor || "#FFFFFF";
                      input.onchange = (e) => {
                        if (e.target instanceof HTMLInputElement) {
                          onBackgroundColorChange(e.target.value);
                        }
                      };
                      input.click();
                    }}
                  />
                </div>
              </div>
            </div>
          )}
        </div>
      </CardContent>
    </Card>
  );
}
